/**
 * Legacy Sidebar Menu Data
 * The complete old-app sidebar tree, copied verbatim from the old app's
 * js/app_v9.js Vue data arrays (ALLAH_secctions, quran_topics, quran_duas,
 * creations, quranic_langs, stories, pillars_of_islam, other_secctions)
 * plus the hard-coded nav items in the old index.html sidebar.
 *
 * Shape: [{ id, bn, en, icon, items: [{ bn, en, partial }...] }...]
 * - bn      : original Bangla label (CONTENT data, not a t() key)
 * - en      : English fallback derived from the partial slug (or hand-mapped)
 * - partial : old-app partial path — page data lives in data/legacy-pages.json
 *             (entry.path === partial), HTML at QuranData.legacyBase + '/partials/' + partial + '.html'
 * Total items: 507 (the old 301-item other_secctions list is split into five
 * thematic groups, order and labels preserved verbatim). Generated 2026-07-11 —
 * do not hand-edit item lists.
 */

const LEGACY_MENU = [
  {
    id: "allah",
    bn: "আল্লাহর",
    en: "Allah",
    icon: "🕋",
    items: [
    {"bn":"৯৯ নাম","en":"Asmaul Husna","partial":"ALLAH/asmaul-husna"},
    {"bn":"স্মরণ","en":"Remembrance","partial":"ALLAH/remembrance"},
    {"bn":"পছন্দ","en":"Likes","partial":"ALLAH/likes"},
    {"bn":"অপছন্দ","en":"Dislikes","partial":"ALLAH/dislikes"},
    {"bn":"পক্ষ থেকে যাদের উপর দুর্ভাগ্য","en":"Woe","partial":"ALLAH/woe"},
    {"bn":"অভিশাপ/অভিসম্পাত","en":"Curse","partial":"ALLAH/curse"},
    {"bn":"শোকর/কৃতজ্ঞতা","en":"Thanks","partial":"ALLAH/thanks"},
    {"bn":"প্রতি সুধারণা","en":"Well Thing","partial":"ALLAH/well-thing"}
    ]
  },
  {
    id: "tilawat",
    bn: "কুরআন তিলাওয়াত+শিক্ষা",
    en: "Quran Recitation & Learning",
    icon: "📖",
    items: [
    {"bn":"কুরআন তিলাওয়াত+শিক্ষা","en":"Quran Recitation & Learning","partial":"quran/tajwid"}
    ]
  },
  {
    id: "duas",
    bn: "কুরআনের দুয়া",
    en: "Quranic Duas",
    icon: "🤲",
    items: [
    {"bn":"সব দুআ একসাথে","en":"All","partial":"quran/dua/all"},
    {"bn":"ঈমান বৃদ্ধির দু'আ","en":"Believe","partial":"quran/dua/believe"},
    {"bn":"ক্ষমা চাওয়ার দু'আ","en":"Forgiveness","partial":"quran/dua/forgiveness"},
    {"bn":"পরিবারের জন্য দু'আ","en":"Family","partial":"quran/dua/family"},
    {"bn":"নিরাপত্তা এবং সুরক্ষার দু'আ","en":"Protection","partial":"quran/dua/protection"},
    {"bn":"পরকালের জন্য দু'আ","en":"Afterlife","partial":"quran/dua/afterlife"},
    {"bn":"অনুগ্রহ  / আশ্রয়","en":"Refgue","partial":"quran/dua/refgue"}
    ]
  },
  {
    id: "topics",
    bn: "বিষয় ভিত্তিক",
    en: "By Topic",
    icon: "📚",
    items: [
    {"bn":"হে মানুষ","en":"Ya Ayyuhannas","partial":"quran/ya-ayyuhannas"},
    {"bn":"হে ঈমানদারগণ","en":"Ya Ayyuhal Lazina Amanu","partial":"quran/ya-ayyuhal-lazina-amanu"},
    {"bn":"সেজদার আয়াত","en":"Sejda","partial":"quran/sejda"},
    {"bn":"উপমা/দৃষ্টান্ত","en":"Parables","partial":"subject/parables"},
    {"bn":"কিয়ামত (পুনরুত্থান দিবস)","en":"Resurrection","partial":"quran/resurrection"},
    {"bn":"আখিরাত","en":"Hereafter","partial":"quran/hereafter"},
    {"bn":"বিচারের দিন","en":"Judgement","partial":"quran/judgement"},
    {"bn":"অন্যায়কারী","en":"Wrongdoer","partial":"quran/wrongdoer"},
    {"bn":"জাহান্নাম/এর অধিবাসী","en":"Hell","partial":"quran/hell"},
    {"bn":"তওবা","en":"Repentance","partial":"quran/repentance"},
    {"bn":"ধৈর্য/সবর","en":"Patience","partial":"quran/patience"},
    {"bn":"ক্ষমা","en":"Forgiveness","partial":"quran/forgiveness"},
    {"bn":"জান্নাত/এর অধিবাসী","en":"Heaven","partial":"quran/heaven"}
    ]
  },
  {
    id: "stories",
    bn: "গল্প /ঘটনা / কাহিনী",
    en: "Stories & Events",
    icon: "📜",
    items: [
    {"bn":"রাসূল ﷺ এর জীবনী","en":"Muhammad S","partial":"stories/muhammad_s"},
    {"bn":"নবীদের জীবন","en":"Messengers","partial":"stories/messengers"},
    {"bn":"সাহাবীদের জীবনী","en":"Companions","partial":"stories/companions"},
    {"bn":"আদম (আ:)","en":"Adam","partial":"stories/adam"},
    {"bn":"নবী ইব্রাহিম (আঃ)","en":"Abraham","partial":"stories/abraham"},
    {"bn":"সালেহ (আঃ)","en":"Salih","partial":"stories/salih"},
    {"bn":"হুদ (আঃ)","en":"Hud","partial":"stories/hud"},
    {"bn":"ইলিয়াস (আঃ)","en":"Elias","partial":"stories/elias"},
    {"bn":"আইয়ুব (আঃ)","en":"Ayub","partial":"stories/ayub"},
    {"bn":"ইয়াকুব (আঃ)","en":"Jacob (Yaqub)","partial":"stories/jacob_(yaqub)"},
    {"bn":"নবী ইউসুফ (আঃ)","en":"Joseph (Yusuf)","partial":"stories/joseph_(yusuf)"},
    {"bn":"নবী লুত (আঃ )","en":"Lot (Lut)","partial":"stories/lot_(lut)"},
    {"bn":"নবী সুলাইমান (আঃ )","en":"Solomon","partial":"stories/solomon"},
    {"bn":"শুয়াইব (আঃ)","en":"Shuayb","partial":"stories/shuayb"},
    {"bn":"দাউদ (আঃ)","en":"David","partial":"stories/_david"},
    {"bn":"সলোমন (আঃ), এবং সাবার রানী","en":"Solomon, And The Queen Of Saba","partial":"stories/_solomon__and_the_queen_of_saba"},
    {"bn":"নূহ (আঃ), এবং অধার্মিক স্ত্রী","en":"Noah, Unrighteous Wife","partial":"stories/_noah__unrighteous_wife"},
    {"bn":"যাকারিয়া (আঃ) দীক্ষাগুরু","en":"John The Baptist","partial":"stories/john_the_baptist"},
    {"bn":"যাকারিয়া (আঃ)","en":"Zachariah","partial":"stories/_zachariah"},
    {"bn":"ইসমাইল (আঃ)","en":"Ishmael (Ismail)","partial":"stories/ishmael_(ismail)"},
    {"bn":"ইসহাক (আঃ)","en":"Isaac (Ishaq)","partial":"stories/_isaac_(ishaq)"},
    {"bn":"ইউনূস (আঃ)","en":"Yunus","partial":"stories/yunus"},
    {"bn":"নবী মূসা (আঃ)","en":"Moses","partial":"stories/moses"},
    {"bn":"মূসা (আঃ) এবং তাঁর সম্প্রদায়ের বাছুর-উপাসনা","en":"Moses, And Calf Worship Of His People","partial":"stories/_moses__and_calf-worship_of_his_people"},
    {"bn":"মূসা (আঃ) এবং তাঁর সম্প্রদায়","en":"Moses, And His People","partial":"stories/moses__and_his_people"},
    {"bn":"হারুন (আঃ)","en":"Aaron","partial":"stories/aaron"},
    {"bn":"মরিয়ম,ঈসা (আঃ) এর সুখবর","en":"Mary, Glad Tidings Of Jesus","partial":"stories/mary__glad_tidings_of_jesus"},
    {"bn":"জিব্রাইল (আঃ)","en":"Gabriel","partial":"stories/gabriel"},
    {"bn":"ঈসা(আ.) এর মা মরিয়ম(আ.)","en":"Mary","partial":"stories/mary"},
    {"bn":"ঈসা (আঃ)","en":"Jesus","partial":"stories/jesus"},
    {"bn":"লুকমান","en":"Luqman","partial":"stories/luqman"},
    {"bn":"যুলকারনাইন","en":"Dhul Qarnayn","partial":"stories/dhul_qarnayn"},
    {"bn":"কারুন","en":"Qarun","partial":"stories/qarun"},
    {"bn":"ফেরাউন","en":"Pharaoh","partial":"stories/pharaoh"},
    {"bn":"আদ জাতি","en":"Aad","partial":"stories/aad"},
    {"bn":"সামুদ জাতি","en":"Thamud","partial":"stories/thamud"},
    {"bn":"লূতের জাতি","en":"Sodomy","partial":"stories/sodomy"}
    ]
  },
  {
    id: "subjects-people",
    bn: "মানুষ ও পরিবার",
    en: "People & Family",
    icon: "👪",
    items: [
    {"bn":"সতর্ককারী","en":"Warner","partial":"subject/warner"},
    {"bn":"দল/বাহিনী","en":"Ahzab","partial":"subject/ahzab"},
    {"bn":"যুগল/দম্পতি","en":"Pair","partial":"subject/pair"},
    {"bn":"মানুষ","en":"Man","partial":"subject/man"},
    {"bn":"অভিভাবক","en":"Guardian","partial":"subject/guardian"},
    {"bn":"ক্রীতদাস","en":"Slaves","partial":"subject/slaves"},
    {"bn":"মাতাপিতা","en":"Parents","partial":"subject/parents"},
    {"bn":"সন্তান","en":"Children","partial":"subject/children"},
    {"bn":"কুমারী","en":"Maiden","partial":"subject/maiden"},
    {"bn":"বোন","en":"Sister","partial":"subject/sister"},
    {"bn":"এতিম","en":"Orphans","partial":"subject/orphans"},
    {"bn":"স্বামী","en":"Husband","partial":"subject/husband"},
    {"bn":"স্ত্রী বউ","en":"Wife","partial":"subject/wife"},
    {"bn":"পত্নী/স্ত্রী","en":"Spouse","partial":"subject/spouse"},
    {"bn":"পুত্রগণ","en":"Sons","partial":"subject/sons"},
    {"bn":"মেয়ে","en":"Girl","partial":"subject/girl"},
    {"bn":"মহিলা","en":"Female","partial":"subject/female"},
    {"bn":"বিচারক","en":"Judge","partial":"subject/judge"},
    {"bn":"আত্মীয়","en":"Relatives","partial":"subject/relatives"},
    {"bn":"মৃত","en":"Dead","partial":"subject/dead"}
    ]
  },
  {
    id: "subjects-nations",
    bn: "দল, জাতি ও সম্প্রদায়",
    en: "Groups, Nations & Communities",
    icon: "👥",
    items: [
    {"bn":"আবরার","en":"Abrar","partial":"subject/abrar"},
    {"bn":"ধার্মিক","en":"Righteous","partial":"subject/righteous"},
    {"bn":"কৃতজ্ঞ","en":"Grateful","partial":"subject/grateful"},
    {"bn":"ধার্মিক","en":"Pious","partial":"subject/pious"},
    {"bn":"দরিদ্র","en":"Poor","partial":"subject/poor"},
    {"bn":"শহীদ","en":"Martyr","partial":"subject/martyr"},
    {"bn":"মুহসিন","en":"Muhsinun","partial":"subject/muhsinun"},
    {"bn":"ধর্মে গোষ্ঠী, গোষ্ঠী এবং বিভাগসমূহ","en":"Sects, Sects And Divisions In Religion","partial":"subject/sects__sects_and_divisions_in_religion"},
    {"bn":"মূর্খ /বোকা","en":"Fool","partial":"subject/fool"},
    {"bn":"একগুঁয়ে","en":"Obstinate","partial":"subject/obstinate"},
    {"bn":"নেতা","en":"Leader","partial":"subject/leader"},
    {"bn":"ধনী","en":"Affluent","partial":"subject/affluent"},
    {"bn":"কাফেলা","en":"Caravan","partial":"subject/caravan"},
    {"bn":"ভ্রমণকারী","en":"Traveller","partial":"subject/traveller"},
    {"bn":"বেদুইন","en":"Bedouin","partial":"subject/bedouin"},
    {"bn":"সৈন্যদল","en":"Troop","partial":"subject/troop"},
    {"bn":"অত্যাচারী/জালিম","en":"Tyrant","partial":"subject/tyrant"},
    {"bn":"মহিলা / নারী","en":"Women","partial":"subject/women"},
    {"bn":"কন্যা","en":"Daughter","partial":"subject/daughter"},
    {"bn":"ইহুদি এবং খ্রিস্টানরা","en":"Jews, And Christians","partial":"subject/jews__and_christians"},
    {"bn":"বধির","en":"Deaf","partial":"subject/deaf"},
    {"bn":"উপজাতি","en":"Tribes","partial":"subject/tribes"},
    {"bn":"কবি","en":"Poet","partial":"subject/poet"},
    {"bn":"ধনী","en":"Rich","partial":"subject/rich"},
    {"bn":"দক্ষ","en":"Skilled","partial":"subject/skilled"},
    {"bn":"বন্দী, যুদ্ধবন্দি","en":"Captives, Prisoners Of War","partial":"subject/captives__prisoners_of_war"},
    {"bn":"সৈন্যবাহিনী","en":"Army","partial":"subject/army"},
    {"bn":"ধার্মিক, জান্নাতে","en":"Righteous, In Paradise","partial":"subject/righteous__in_paradise"},
    {"bn":"নারী, সতী-সাধ্বী নারীকে দোষারোপ","en":"Women, Who Accuse Chaste Women","partial":"subject/women__who_accuse_chaste_women"},
    {"bn":"বন্ধু","en":"Friends","partial":"subject/friends"},
    {"bn":"পথিক","en":"Wayfarer","partial":"subject/wayfarer"},
    {"bn":"পরামর্শ","en":"Counsel","partial":"subject/counsel"},
    {"bn":"ঠকবাজ","en":"Fraud","partial":"subject/fraud"},
    {"bn":"হতভাগ্য","en":"Wretched","partial":"subject/wretched"},
    {"bn":"মাদইয়ানবাসী","en":"Madyan","partial":"subject/madyan"},
    {"bn":"মুমিন","en":"Believers","partial":"subject/believers"},
    {"bn":"অত্যাচারী জুলুমকারী নির্যাতনকারী","en":"Wrongdoer","partial":"subject/wrongdoer"},
    {"bn":"শয়তান","en":"Satan","partial":"subject/satan"},
    {"bn":"শয়ত্বান","en":"Devil","partial":"subject/devil"},
    {"bn":"ইহুদী","en":"Jews","partial":"subject/jews"},
    {"bn":"বনী-ইসরাঈল","en":"Israel, Children Of Israel","partial":"subject/israel__children_of_israel"},
    {"bn":"রানী শেবা","en":"Queen Sheba","partial":"subject/queen_sheba"},
    {"bn":"ইসরাঈলের বংশধর","en":"Children, Of Israel","partial":"subject/children__of_israel"},
    {"bn":"ইবলিস","en":"Iblis","partial":"subject/iblis"},
    {"bn":"অনুগ্রহকারী","en":"Benefactors","partial":"subject/benefactors"},
    {"bn":"মুনাফিক","en":"Hypocrites","partial":"subject/hypocrites"},
    {"bn":"অকৃতজ্ঞ","en":"Ungrateful","partial":"subject/ungrateful"},
    {"bn":"খ্রিস্টান","en":"Christians","partial":"subject/christians"},
    {"bn":"বাসিন্দা","en":"Inhabitant","partial":"subject/inhabitant"},
    {"bn":"জাতি","en":"Race","partial":"subject/race"},
    {"bn":"ভ্রাতৃত্ব","en":"Brotherhood","partial":"subject/brotherhood"}
    ]
  },
  {
    id: "subjects-faith",
    bn: "ঈমান ও নেক আমল",
    en: "Faith & Good Deeds",
    icon: "💠",
    items: [
    {"bn":"জ্ঞান","en":"Knowledge","partial":"subject/knowledge"},
    {"bn":"বিজ্ঞতা/পাণ্ডিত্য","en":"Wisdom","partial":"subject/wisdom"},
    {"bn":"প্রার্থনা","en":"Prayer","partial":"subject/prayer"},
    {"bn":"ইবাদত","en":"Worship","partial":"subject/worship"},
    {"bn":"ধন-সম্পদ","en":"Wealth","partial":"subject/wealth"},
    {"bn":"সাক্ষী","en":"Witness","partial":"subject/witness"},
    {"bn":"দান","en":"Charity","partial":"subject/charity"},
    {"bn":"নৈতিক আদেশ উপদেশ","en":"Commandments","partial":"subject/commandments"},
    {"bn":"আদেশ","en":"Command","partial":"subject/command"},
    {"bn":"পথপ্রদর্শন","en":"Guidance","partial":"subject/guidance"},
    {"bn":"প্রশংসা স্তুতি গুণগান","en":"Praise","partial":"subject/praise"},
    {"bn":"সাবধানবাণী সতর্কীকরণ","en":"Warning","partial":"subject/warning"},
    {"bn":"অদৃশ্য গায়েব","en":"Unseen","partial":"subject/unseen"},
    {"bn":"প্রতিদান প্রতিফল","en":"Repayment","partial":"subject/repayment"},
    {"bn":"একেশ্বরবাদ","en":"Monotheism","partial":"subject/monotheism"},
    {"bn":"প্রশংসা","en":"Glorification","partial":"subject/glorification"},
    {"bn":"সাফল্য","en":"Success","partial":"subject/success"},
    {"bn":"যথার্থতা / ন্যায্যতা","en":"Exactitude","partial":"subject/exactitude"},
    {"bn":"বৈধ","en":"Lawful","partial":"subject/lawful"},
    {"bn":"খাদ্য, হালাল এবং বেআইনী (হালাল ও হারাম) খাবার","en":"Food, Lawful And Unlawful, Halal And Haram, Food","partial":"subject/food__lawful_and_unlawful__halal_and_haram__food"},
    {"bn":"অঙ্গীকার / চুক্তিপত্র","en":"Covenants","partial":"subject/covenants"},
    {"bn":"মানুষ, মানুষের কর্তব্য","en":"Man, Duty Of Man","partial":"subject/man__duty_of_man"},
    {"bn":"স্মরণ করাইয়া দেত্তয়া","en":"Reminder","partial":"subject/reminder"},
    {"bn":"আত্মা","en":"Spirit","partial":"subject/spirit"},
    {"bn":"ভালবাসা","en":"Love","partial":"subject/love"},
    {"bn":"সাদাকাহ (দান )","en":"Sadaqah, Charity","partial":"subject/sadaqah__charity_"},
    {"bn":"ভোর/ফজর","en":"Dawn","partial":"subject/dawn"},
    {"bn":"অনুপ্রেরণা","en":"Inspiration","partial":"subject/inspiration"},
    {"bn":"মজুরি","en":"Wage","partial":"subject/wage"},
    {"bn":"শপথ / প্রতিজ্ঞা","en":"Oaths","partial":"subject/oaths"},
    {"bn":"অনুমোদন","en":"Granting","partial":"subject/granting"},
    {"bn":"মুক্তিপণ","en":"Ransom","partial":"subject/ransom"},
    {"bn":"উত্তরাধিকার","en":"Inheritance","partial":"subject/inheritance"},
    {"bn":"ভাগ্য","en":"Destiny","partial":"subject/destiny"},
    {"bn":"আচরণ","en":"Behaviour","partial":"subject/behaviour"},
    {"bn":"ধৈর্য","en":"Patience","partial":"subject/patience"},
    {"bn":"পরীক্ষা","en":"Trial","partial":"subject/trial"},
    {"bn":"বিজয়","en":"Victory","partial":"subject/victory"},
    {"bn":"লড়াই","en":"Fighting","partial":"subject/fighting"},
    {"bn":"বিবাহ","en":"Marriage","partial":"subject/marriage"},
    {"bn":"চুক্তি","en":"Pact","partial":"subject/pact"},
    {"bn":"করুণা","en":"Mercy","partial":"subject/mercy"},
    {"bn":"আহার করা / খাদ্যগ্রহণ করা","en":"Eating","partial":"subject/eating"},
    {"bn":"পুনরুত্থান দিবস","en":"Resurrection Day, Deniers Of Resurrection Day","partial":"subject/resurrection_day__deniers_of_resurrection_day"},
    {"bn":"পুরস্কার","en":"Reward","partial":"subject/reward"},
    {"bn":"যাকাত","en":"Zakat","partial":"subject/zakat"},
    {"bn":"নিশ্চয়তা","en":"Certainty","partial":"subject/certainty"},
    {"bn":"মহাজাগতিক সংক্রান্ত","en":"Celestial Mechanics","partial":"subject/celestial_mechanics"},
    {"bn":"গন্তব্য / লক্ষ্য","en":"Destination","partial":"subject/destination"},
    {"bn":"মধ্যস্থতা","en":"Intercession","partial":"subject/intercession"},
    {"bn":"মৃত্যু","en":"Dead, Death","partial":"subject/dead__death"},
    {"bn":"আখেরাতের দিন","en":"Last Day","partial":"subject/last_day"},
    {"bn":"মানুষ ৩ ভাগে বিভক্ত হবে","en":"Man, Sorted Out Into Three Classes","partial":"subject/man__sorted_out_into_three_classes"},
    {"bn":"পার্থক্য","en":"Difference","partial":"subject/difference"},
    {"bn":"নম্রতা","en":"Humility","partial":"subject/humility"},
    {"bn":"ভ্রমণ","en":"Travel","partial":"subject/travel"},
    {"bn":"জিহাদ","en":"Jihad","partial":"subject/jihad"},
    {"bn":"আনন্দ","en":"Joy","partial":"subject/joy"},
    {"bn":"দান / সাহায্য","en":"Help","partial":"advice_instructions/help"},
    {"bn":"দান , সাদাকাহ","en":"Charity, Sadaqah","partial":"subject/charity__sadaqah"},
    {"bn":"উপহার","en":"Gift","partial":"subject/gift"},
    {"bn":"আল্লাহর পথে ব্যয় কর","en":"Spend, In Allah's Cause","partial":"subject/spend__in_allah's_cause"},
    {"bn":"হাসি","en":"Laughter","partial":"subject/laughter"},
    {"bn":"দৃষ্টান্ত, বাগানের মালিক","en":"Parables, People Of The Garden","partial":"subject/parables__people_of_the_garden"},
    {"bn":"শোভা-সৌন্দর্য","en":"Adornment","partial":"subject/adornment"},
    {"bn":"দৃষ্টান্ত , জনপদবাসীদের কথা","en":"Parables, Dwellers Of The Town","partial":"subject/parables__dwellers_of_the_town"},
    {"bn":"সাজদাহ","en":"Prostration","partial":"subject/prostration"},
    {"bn":"ধার্মিকতা","en":"Righteousness","partial":"subject/righteousness"},
    {"bn":"মানুষ, স্ত্রী এবং শিশুরা, যখন দুঃখ ক্লেশ স্পর্শ করে","en":"Man, Wife And Children, When Harm Or Evil Touches","partial":"subject/man__wife_and_children__when_harm_or_evil_touches"},
    {"bn":"বিজ্ঞপ্তি","en":"Notification","partial":"subject/notification"},
    {"bn":"আনুগত্য","en":"Obedience","partial":"subject/obedience"},
    {"bn":"ইচ্ছা/ইচ্ছাশক্তি","en":"Wills","partial":"subject/wills"},
    {"bn":"ঈমান বিশ্বাস","en":"Faith, Belief","partial":"subject/faith__belief_"},
    {"bn":"ধ্যান / চিন্তা-ভাবনা","en":"Meditation","partial":"subject/meditation"},
    {"bn":"আল্লাহর ইচ্ছা","en":"Will Of Allah","partial":"subject/will_of_allah"},
    {"bn":"অধ্যয়ন","en":"Studying","partial":"subject/studying"},
    {"bn":"কাজ","en":"Work","partial":"subject/work"},
    {"bn":"চুক্তি","en":"Agreement","partial":"subject/agreement"},
    {"bn":"দায়িত্ব","en":"Duty","partial":"subject/duty"},
    {"bn":"চুক্তি","en":"Treaty","partial":"subject/treaty"},
    {"bn":"আস্থা/বিশ্বাস","en":"Trust","partial":"subject/trust"},
    {"bn":"দুর্বলতা","en":"Weakness","partial":"subject/weakness"},
    {"bn":"ছদ্মবেশ","en":"Cloak","partial":"subject/cloak"}
    ]
  },
  {
    id: "subjects-vices",
    bn: "পাপ, পরীক্ষা ও মন্দ স্বভাব",
    en: "Sins, Trials & Vices",
    icon: "⚠️",
    items: [
    {"bn":"হিংসা","en":"Envy","partial":"subject/envy"},
    {"bn":"ভণ্ডামি, তাদের অন্তরে রোগ","en":"Hypocrites, Disease In Their Hearts","partial":"subject/hypocrites__disease_in_their_hearts"},
    {"bn":"দু:খ প্রকাশ","en":"Regret","partial":"subject/regret"},
    {"bn":"গ্লানি /পরিশ্রান্তি","en":"Tiredness","partial":"subject/tiredness"},
    {"bn":"কষ্ট","en":"Hardship","partial":"subject/hardship"},
    {"bn":"ঘৃণা","en":"Hatred","partial":"subject/hatred"},
    {"bn":"সুদ (রিবা)","en":"Usury, Riba","partial":"subject/usury__riba_"},
    {"bn":"ভীরুতা","en":"Cowardice","partial":"subject/cowardice"},
    {"bn":"অহংকার দাম্ভিকতা","en":"Arrogance","partial":"subject/arrogance"},
    {"bn":"ভয়","en":"Fear","partial":"subject/fear"},
    {"bn":"জাদু","en":"Sorcery","partial":"subject/sorcery"},
    {"bn":"দিন","en":"Day","partial":"subject/day"},
    {"bn":"অনুগ্রহ","en":"Blessing","partial":"subject/blessing"},
    {"bn":"সংবাদ","en":"News","partial":"subject/news"},
    {"bn":"স্বাস্থ্য","en":"Health","partial":"subject/health"},
    {"bn":"শুক্রবিন্দু","en":"Drop","partial":"subject/drop"},
    {"bn":"গোপন","en":"Secret","partial":"subject/secret"},
    {"bn":"দুর্ভোগ দুদর্শা দুরবস্থা","en":"Adversity","partial":"subject/adversity"},
    {"bn":"ক্ষতি","en":"Loss","partial":"subject/loss"},
    {"bn":"বোঝা দায়িত্ব চাপা","en":"Burden","partial":"subject/burden"},
    {"bn":"অবিশ্বাসী কাফের","en":"Disbelievers","partial":"subject/disbelievers"},
    {"bn":"বিপথগামী পথভ্রান্ত","en":"Astray","partial":"subject/astray"},
    {"bn":"প্রতিবন্ধকতা / বাধা","en":"Obstruction","partial":"subject/obstruction"},
    {"bn":"দুর্নীতি","en":"Corruption","partial":"subject/corruption"},
    {"bn":"নিষিদ্ধ","en":"Forbidden","partial":"subject/forbidden"},
    {"bn":"অনুতাপ","en":"Repentance","partial":"subject/repentance"},
    {"bn":"বিপর্যয়","en":"Calamities","partial":"subject/calamities"},
    {"bn":"ব্যভিচার","en":"Justice, Adl","partial":"subject/justice__adl_"},
    {"bn":"ব্যভিচার","en":"Adultery","partial":"subject/adultery"},
    {"bn":"উপহাস","en":"Mockery","partial":"subject/mockery"},
    {"bn":"অভিশাপ","en":"Curse","partial":"subject/curse"},
    {"bn":"লোভ","en":"Greed","partial":"subject/greed"},
    {"bn":"উপভোগ","en":"Enjoyment","partial":"subject/enjoyment"},
    {"bn":"বিবাহবিচ্ছেদ","en":"Divorce","partial":"subject/divorce"},
    {"bn":"অংশীদার","en":"Partner","partial":"subject/partner"},
    {"bn":"সন্দেহ","en":"Doubt","partial":"subject/doubt"},
    {"bn":"ধর্মত্যাগ","en":"Apostasy","partial":"subject/apostasy"},
    {"bn":"হত্যাকাণ্ড","en":"Killing","partial":"subject/killing"},
    {"bn":"অজ্ঞতা","en":"Ignorance","partial":"subject/ignorance"},
    {"bn":"অশুভ","en":"Evil","partial":"subject/evil"},
    {"bn":"মিথ্যা কথা","en":"Falsehood","partial":"subject/falsehood"},
    {"bn":"মিথ্যা","en":"Lie","partial":"subject/lie"},
    {"bn":"শয়তানী শক্তি","en":"Taghut","partial":"subject/taghut"},
    {"bn":"অপমান","en":"Abasement","partial":"subject/abasement"},
    {"bn":"শত্রুতা","en":"Hostility","partial":"subject/hostility"},
    {"bn":"প্রতিশোধ","en":"Revenge","partial":"subject/revenge"},
    {"bn":"পাপ","en":"Sin","partial":"subject/sin"},
    {"bn":"দোষারোপ","en":"Blame","partial":"subject/blame"},
    {"bn":"বিশ্বাসঘাতকতা","en":"Infidelity","partial":"subject/infidelity"},
    {"bn":"ঔদ্ধত্য","en":"Insolence","partial":"subject/insolence"},
    {"bn":"যন্ত্রণা","en":"Torment","partial":"subject/torment"},
    {"bn":"ত্যাগ","en":"Sacrifice","partial":"subject/sacrifice"},
    {"bn":"উল্লাস","en":"Exultation","partial":"subject/exultation"},
    {"bn":"পদচিহ্ন","en":"Footsteps","partial":"subject/footsteps"},
    {"bn":"ছাঁচ/প্যাটার্ন","en":"Pattern","partial":"subject/pattern"},
    {"bn":"সম্পত্তি","en":"Property","partial":"subject/property"},
    {"bn":"ইচ্ছা","en":"Desires","partial":"subject/desires"},
    {"bn":"ইস্রায়েল, তাদের চুক্তি","en":"Israel, Their Covenants","partial":"subject/israel__their_covenants"},
    {"bn":"মানুষ, তৈরি এবং সমৃদ্ধ","en":"Man, Created And Endowed With","partial":"subject/man__created_and_endowed_with"},
    {"bn":"মুহাম্মদ(সাঃ), মুহাম্মদ(সাঃ) সালাত আদায়","en":"Muhammad, Muhammad Devoted To Prayer","partial":"subject/muhammad__muhammad_devoted_to_prayer"},
    {"bn":"মুহাম্মদ(সাঃ), মুহাম্মদ(সাঃ) এর উক্তি","en":"Muhammad, His Sayings","partial":"subject/muhammad__his_sayings_"},
    {"bn":"গোপনীয়তা","en":"Privacy","partial":"subject/privacy"},
    {"bn":"যৌন সম্পর্ক","en":"Sexual Relations","partial":"subject/sexual_relations"},
    {"bn":"চুরি","en":"Theft","partial":"subject/theft"},
    {"bn":"প্রাচীর","en":"Wall","partial":"subject/wall"},
    {"bn":"বিপর্যয়","en":"Disaster","partial":"subject/disaster"},
    {"bn":"অসুস্থতা","en":"Illness","partial":"subject/illness"},
    {"bn":"নিপীড়ন","en":"Persecution","partial":"subject/persecution"},
    {"bn":"বিশ্বাসঘাতকতা","en":"Betrayal","partial":"subject/betrayal"},
    {"bn":"লুঠ","en":"Booty","partial":"subject/booty"},
    {"bn":"শাস্তি","en":"Penalty","partial":"subject/penalty"},
    {"bn":"তৃষ্ণা","en":"Thirst","partial":"subject/thirst"},
    {"bn":"প্রকৃতিবাদ","en":"Materialism","partial":"subject/materialism"}
    ]
  },
  {
    id: "subjects-misc",
    bn: "কিতাব, ইতিহাস ও বিবিধ বিষয়",
    en: "Scripture, History & More",
    icon: "📜",
    items: [
    {"bn":"উদ্ঘাটন","en":"Revelation","partial":"subject/revelation"},
    {"bn":"সাদা","en":"White","partial":"subject/white"},
    {"bn":"পূর্ব পশ্চিম","en":"East West","partial":"subject/east_west"},
    {"bn":"মানুষের সৃষ্টি","en":"Creation, Of Man","partial":"subject/creation__of_man"},
    {"bn":"পূর্বপুরুষ বাপ-দাদা","en":"Ancestors","partial":"subject/ancestors"},
    {"bn":"জমায়েত","en":"Gathering","partial":"subject/gathering"},
    {"bn":"খ্রীষ্টের উপদেশাবলী","en":"Gospel","partial":"subject/gospel"},
    {"bn":"ধর্মগ্রন্থ","en":"Scriptures","partial":"subject/scriptures"},
    {"bn":"বাইবেল","en":"Bible","partial":"subject/bible"},
    {"bn":"ইসলাম","en":"Islam","partial":"subject/islam"},
    {"bn":"কাফের এবং মুহাম্মদ (সাঃ)","en":"Disbelievers, And Muhammad, Saw","partial":"subject/disbelievers__and_muhammad__saw_"},
    {"bn":"মুহাম্মদ(সাঃ), মুহাম্মাদ(সাঃ) এর পরিবার সম্পর্কে আয়াত","en":"Muhammad, Ayat Regarding Family Of Muhammad","partial":"subject/muhammad__ayat_regarding_family_of_muhammad"},
    {"bn":"ধর্মগ্রন্থ, ইহুদি এবং খ্রিস্টানগণ","en":"Scriptures, People Of The, Jews And Christians","partial":"subject/scriptures__people_of_the__jews_and_christians_"},
    {"bn":"আল্লাহ ব্যতীত মিথ্যা উপাস্য, মূর্তি এবং তথাকথিত অংশীদার","en":"False Gods, Idols And So Called Partners Besides Allah","partial":"subject/false_gods__idols_and_so-called_partners_besides_allah"},
    {"bn":"প্রার্থনার সময়","en":"Prayer, Times","partial":"subject/prayer__times"},
    {"bn":"যৌনসহবাস","en":"Sexes","partial":"subject/sexes"},
    {"bn":"ইস্রায়েল, বনী ইস্রায়েল আল্লাহর আনুগত্যের বিরুদ্ধে বিদ্রোহ","en":"Israel, Children Of Israel Rebelling Against Allah's Obedience","partial":"subject/israel__children_of_israel_rebelling_against_allah's_obedience"},
    {"bn":"মূসা, দুই সমুদ্রের সংযোগস্থল","en":"Moses, To The Junction Of The Two Seas","partial":"subject/moses__to_the_junction_of_the_two_seas"},
    {"bn":"তীর্থযাত্রা","en":"Pilgrimage","partial":"subject/pilgrimage"},
    {"bn":"প্রজন্ম","en":"Generation","partial":"subject/generation"},
    {"bn":"মানুষ, বাম হাতের সাহাবী","en":"Man, Companions Of Left Hand","partial":"subject/man__companions_of_left_hand"},
    {"bn":"উহুদ","en":"Uhud","partial":"subject/uhud"},
    {"bn":"গুহা, গুহার লোক","en":"Cave, People Of The Cave","partial":"subject/cave__people_of_the_cave"},
    {"bn":"উন্মত্ততা/পাগলামি","en":"Madness","partial":"subject/madness"},
    {"bn":"মুহাম্মদ(সাঃ), জিব্রাইল কে দেখেছেন","en":"Muhammad, Saw Gabriel","partial":"subject/muhammad__saw_gabriel"},
    {"bn":"জ্বলন্ত আগুন","en":"Blaze","partial":"subject/blaze"},
    {"bn":"মানুষ, তার অহংকার","en":"Man, His Arrogance","partial":"subject/man__his_arrogance"},
    {"bn":"ফেরাউন, ফেরাউনের পরিবারের একজন বিশ্বাসী লোক","en":"Pharaoh, A Believing Man From Pharaoh's Family","partial":"subject/pharaoh__a_believing_man_from_pharaoh's_family"},
    {"bn":"পরিখা / খন্দক","en":"Trench","partial":"subject/trench"},
    {"bn":"দেশান্তরে গমন","en":"Migration","partial":"subject/migration"},
    {"bn":"তাবুক","en":"Tabuk","partial":"subject/tabuk"},
    {"bn":"দলিল/প্রমাণ/লেখ্য","en":"Record","partial":"subject/record"},
    {"bn":"রাজত্বকাল","en":"Kingship","partial":"subject/kingship"},
    {"bn":"অংশীদার, আল্লাহর অংশীদার, একটি মিথ্যাবাদী","en":"Partner, Partners Of Allah, A Falsehood","partial":"subject/partner__partners_of_allah__a_falsehood"},
    {"bn":"নিরাপত্তা","en":"Security","partial":"subject/security"},
    {"bn":"মক্কা (বাক্কা)","en":"Makkah, Bakkah","partial":"subject/makkah__bakkah_"},
    {"bn":"অতিরিক্ত","en":"Excess","partial":"subject/excess"},
    {"bn":"কাবা","en":"Kaaba","partial":"subject/kaaba"},
    {"bn":"মানুষ, ডান হাতের সাহাবী","en":"Man, Companions Of Right Hand","partial":"subject/man__companions_of_right_hand"},
    {"bn":"মানুষ, নামায আদায়কারী","en":"Man, Devoted To Prayers","partial":"subject/man__devoted_to_prayers"},
    {"bn":"পরিমাপ করা","en":"Measure","partial":"subject/measure"},
    {"bn":"শক্তিহীনতা","en":"Powerlessness","partial":"subject/powerlessness"},
    {"bn":"সতীত্ব","en":"Chastity","partial":"subject/chastity"},
    {"bn":"অনুমান","en":"Conjecture","partial":"subject/conjecture"},
    {"bn":"ব্যাখ্যা","en":"Interpretation","partial":"subject/interpretation"},
    {"bn":"অর্থ","en":"Meaning","partial":"subject/meaning"},
    {"bn":"ভারসাম্য","en":"Balance","partial":"subject/balance"},
    {"bn":"মোহর (দাম্পত্য-অর্থ)","en":"Mahr, Bridal Money","partial":"subject/mahr__bridal-money_"},
    {"bn":"সংগ্রাম / লড়াই","en":"Striving","partial":"subject/striving"},
    {"bn":"মুনাফিক ও কাফেরদের হৃদয়ে রোগ","en":"Disease In The Hearts Of Hypocrites And Disbelievers","partial":"subject/disease_in_the_hearts_of_hypocrites_and_disbelievers"},
    {"bn":"হজ","en":"Hajj, Pilgrimage","partial":"subject/hajj__pilgrimage_"},
    {"bn":"হৃদয়, যার হৃদয়ে একটি রোগ আছে","en":"Hearts, In Whose Hearts There Is A Disease","partial":"subject/hearts__in_whose_hearts_there_is_a_disease"},
    {"bn":"জামা","en":"Shirt","partial":"subject/shirt"},
    {"bn":"অপরাধ","en":"Crime","partial":"subject/crime"},
    {"bn":"পানপাত্র","en":"Cup","partial":"subject/cup"},
    {"bn":"ক্ষুধা","en":"Hunger","partial":"subject/hunger"},
    {"bn":"বিশ্বস্ত","en":"Trustworthy","partial":"subject/trustworthy"},
    {"bn":"আল্লাহর চেহারা বা মুখোমুখি","en":"Face Or Countenance Of Allah","partial":"subject/face_or_countenance_of_allah"},
    {"bn":"মালপত্র","en":"Goods","partial":"subject/goods"},
    {"bn":"মুহাম্মদ(সাঃ), এবং অন্ধ মানুষ","en":"Muhammad, And The Blind Man","partial":"subject/muhammad__and_the_blind_man"},
    {"bn":"দলাদলি","en":"Faction","partial":"subject/faction"},
    {"bn":"সিয়াম / রোজা","en":"Fasting","partial":"subject/fasting"},
    {"bn":"বিজয়ী","en":"Victorious","partial":"subject/victorious"},
    {"bn":"প্রমান","en":"Evidence","partial":"subject/evidence"},
    {"bn":"মূসা, সঠিক পথে পরিচালিত","en":"Moses, Guided To The Right Path","partial":"subject/moses__guided_to_the_right_path"},
    {"bn":"উপদেশ","en":"Admonition","partial":"subject/admonition"},
    {"bn":"বিধান","en":"Provision","partial":"subject/provision"},
    {"bn":"কবর","en":"Grave","partial":"subject/grave"},
    {"bn":"উপত্যকা","en":"Valley","partial":"subject/valley"},
    {"bn":"পৃথিবী, ভূমিকম্প","en":"Earth, Earthquake","partial":"subject/earth__earthquake"},
    {"bn":"বিভক্তি-প্রাচীর","en":"Barzakh","partial":"subject/barzakh"},
    {"bn":"ভ্রূণতত্ত্ব","en":"Embryology","partial":"subject/embryology"},
    {"bn":"গর্ভাবস্থা","en":"Pregnancy","partial":"subject/pregnancy"},
    {"bn":"জবাই","en":"Slaughter","partial":"subject/slaughter"}
    ]
  },
  {
    id: "creations",
    bn: "বিবিধ সৃষ্টি",
    en: "Creations",
    icon: "🌿",
    items: [
    {"bn":"সৃষ্টি","en":"Creation","partial":"creations/creation"},
    {"bn":"আলো","en":"Light","partial":"creations/light"},
    {"bn":"ফেরেশতা","en":"Angels","partial":"creations/angels"},
    {"bn":"মহাবিশ্ব","en":"Universe","partial":"creations/universe"},
    {"bn":"মহাবিশ্ব গতি","en":"Universe Motion","partial":"creations/universe_motion"},
    {"bn":"বিশ্বজগৎ","en":"World","partial":"creations/world"},
    {"bn":"জ্যোতির্বিদ্যা নক্ষত্রবিজ্ঞান","en":"Astronomy","partial":"creations/astronomy"},
    {"bn":"সূর্য","en":"Sun","partial":"creations/sun"},
    {"bn":"চন্দ্র","en":"Moon","partial":"creations/moon"},
    {"bn":"পৃথিবী","en":"Earth","partial":"creations/earth"},
    {"bn":"পৃথিবী, ঘূর্ণন","en":"Earth, Rotation","partial":"creations/earth__rotation"},
    {"bn":"আবহাওয়া","en":"Weather","partial":"creations/weather"},
    {"bn":"বাতাস","en":"Wind","partial":"creations/wind"},
    {"bn":"ধুলা","en":"Dust","partial":"creations/dust"},
    {"bn":"ধোঁয়া","en":"Smoke","partial":"creations/smoke"},
    {"bn":"জিন","en":"Jinn","partial":"creations/jinn"},
    {"bn":"জোড়ায়, সৃষ্টি","en":"Creation, In Pairs","partial":"creations/creation__in_pairs"},
    {"bn":"মানবজাতি","en":"Humankind","partial":"creations/humankind"},
    {"bn":"পাহাড় পর্বতমালা","en":"Mountains","partial":"creations/mountains"},
    {"bn":"মাটি","en":"Soil","partial":"creations/soil"},
    {"bn":"সাগর","en":"Sea","partial":"creations/sea"},
    {"bn":"দিগন্ত","en":"Horizon","partial":"creations/horizon"},
    {"bn":"সমুদ্র, দুই সমুদ্র","en":"Sea, The Two Seas","partial":"creations/sea__the_two_seas"},
    {"bn":"বাগান উদ্যান","en":"Garden","partial":"creations/garden"},
    {"bn":"শহর","en":"City","partial":"creations/city"},
    {"bn":"নদী","en":"River","partial":"creations/river"},
    {"bn":"নৌকা","en":"Ark","partial":"creations/ark"},
    {"bn":"চোখ","en":"Eye","partial":"creations/eye"},
    {"bn":"মানুষ, হইতে সৃষ্ট","en":"Man, Created From","partial":"creations/man__created_from"},
    {"bn":"জমি","en":"Land","partial":"creations/land"},
    {"bn":"গবাদি পশু","en":"Cattle","partial":"creations/cattle"},
    {"bn":"উট","en":"Camel","partial":"creations/camel"},
    {"bn":"জীবজন্তু","en":"Animals","partial":"creations/animals"},
    {"bn":"জাহাজ","en":"Ships","partial":"creations/ships"},
    {"bn":"সম্প্রদায়","en":"Community","partial":"creations/community"},
    {"bn":"হাড়/অস্থি","en":"Bone","partial":"creations/bone"},
    {"bn":"জীব","en":"Creatures","partial":"creations/creatures"},
    {"bn":"পাখি","en":"Birds","partial":"creations/birds"},
    {"bn":"মেঘ","en":"Clouds","partial":"creations/clouds"},
    {"bn":"জন্তু জানোয়ার","en":"Dawabb","partial":"creations/dawabb"},
    {"bn":"কান","en":"Ear","partial":"creations/ear"},
    {"bn":"ফসল","en":"Crops","partial":"creations/crops"},
    {"bn":"ঘোড়া","en":"Horse","partial":"creations/horse"},
    {"bn":"গাভী","en":"Cow","partial":"creations/cow"},
    {"bn":"বাছুর","en":"Calf","partial":"creations/calf"},
    {"bn":"সোনার বাছুর","en":"Golden Calf","partial":"creations/golden_calf"},
    {"bn":"বাতি","en":"Lamp","partial":"creations/lamp"},
    {"bn":"খেজুর গাছ","en":"Palms","partial":"creations/palms"},
    {"bn":"কণ্ঠস্বর/বাচ্য","en":"Voice","partial":"creations/voice"},
    {"bn":"উদ্ভিদ","en":"Plant","partial":"creations/plant"},
    {"bn":"পানীয়","en":"Drink","partial":"creations/drink"},
    {"bn":"কণ্ঠনালী","en":"Throat","partial":"creations/throat"},
    {"bn":"ঝরনা","en":"Fountain","partial":"creations/fountain"},
    {"bn":"সবুজ","en":"Green","partial":"creations/green"},
    {"bn":"পাহাড়","en":"Hill","partial":"creations/hill"},
    {"bn":"তরঙ্গ","en":"Wave","partial":"creations/wave"},
    {"bn":"পিতল","en":"Brass","partial":"creations/brass"},
    {"bn":"পথ","en":"Path","partial":"creations/path"},
    {"bn":"লোহিত সাগর","en":"Red Sea","partial":"creations/red_sea"},
    {"bn":"গাছ","en":"Trees","partial":"creations/trees"},
    {"bn":"জানোয়ার","en":"Beasts","partial":"creations/beasts"},
    {"bn":"পূর্বাহ্ন","en":"Forenoon","partial":"creations/forenoon"},
    {"bn":"ফল","en":"Fruit","partial":"creations/fruit"},
    {"bn":"শিলা/পাথর","en":"Rock","partial":"creations/rock"},
    {"bn":"জ্বালানি","en":"Firewood","partial":"creations/firewood"},
    {"bn":"মেষ","en":"Sheep","partial":"creations/sheep"},
    {"bn":"পেট","en":"Belly","partial":"creations/belly"},
    {"bn":"গাধা","en":"Donkeys","partial":"creations/donkeys"},
    {"bn":"শূকর","en":"Swine","partial":"creations/swine"},
    {"bn":"পরমাণু","en":"Atom","partial":"creations/atom"},
    {"bn":"উল্কা","en":"Meteor","partial":"creations/meteor"},
    {"bn":"সিনাই","en":"Sinai","partial":"creations/sinai"},
    {"bn":"বীজ, কে এটি বাড়ায়","en":"Seed, Who Makes It Grow","partial":"creations/seed__who_makes_it_grow"},
    {"bn":"সকাল","en":"Morning","partial":"creations/morning"},
    {"bn":"বৃষ্টি","en":"Rain","partial":"creations/rain"},
    {"bn":"খাদ্যদ্রব্য","en":"Food","partial":"creations/food"},
    {"bn":"পাথর","en":"Stones","partial":"creations/stones"},
    {"bn":"যাক্কুম","en":"Zaqqum","partial":"creations/zaqqum"},
    {"bn":"বই","en":"Books","partial":"creations/books"},
    {"bn":"গর্ভ","en":"Womb","partial":"creations/womb"},
    {"bn":"ভবন/অট্টালিকা","en":"Building","partial":"creations/building"},
    {"bn":"আবরণ","en":"Cover","partial":"creations/cover"},
    {"bn":"বন্যা","en":"Flood","partial":"creations/flood"},
    {"bn":"আকাশ","en":"Sky","partial":"creations/sky"},
    {"bn":"রঙ","en":"Colour","partial":"creations/colour"},
    {"bn":"স্বপ্ন","en":"Dream","partial":"creations/dream"},
    {"bn":"আঙ্গুর","en":"Grapes","partial":"creations/grapes"},
    {"bn":"গুপ্তধন","en":"Treasure","partial":"creations/treasure"},
    {"bn":"দৃষ্টি","en":"Vision","partial":"creations/vision"},
    {"bn":"মাছ","en":"Fish","partial":"creations/fish"},
    {"bn":"হাতি","en":"Elephant","partial":"creations/elephant"},
    {"bn":"বরই গাছ","en":"Lote Tree","partial":"creations/lote_tree"},
    {"bn":"অলঙ্কার","en":"Ornament","partial":"creations/ornament"},
    {"bn":"ঔষধি","en":"Herb","partial":"creations/herb"},
    {"bn":"ঘুম","en":"Sleep","partial":"creations/sleep"},
    {"bn":"সাপ","en":"Snake","partial":"creations/snake"},
    {"bn":"চিহ্ন/নিদর্শন","en":"Sign","partial":"creations/sign"},
    {"bn":"রূপা","en":"Silver","partial":"creations/silver"},
    {"bn":"স্বর্গ, খাঁটি সিলযুক্ত ওয়াইন, সাদা, সুস্বাদু","en":"Paradise, Pure Sealed Wine, White, Delicious","partial":"creations/paradise__pure_sealed_wine__white__delicious"},
    {"bn":"যাক্কুম গাছ","en":"Tree Zaqqum","partial":"creations/tree_zaqqum"},
    {"bn":"জল, দুই সমুদ্র","en":"Water, Two Seas","partial":"creations/water__two_seas"},
    {"bn":"ধাতুবিদ্যা","en":"Metallurgy","partial":"creations/metallurgy"},
    {"bn":"হৃদয়, সীল","en":"Hearts, Sealed","partial":"creations/hearts__sealed"},
    {"bn":"চাবি","en":"Key","partial":"creations/key"},
    {"bn":"পশম","en":"Wool","partial":"creations/wool"},
    {"bn":"জিহ্বা","en":"Tongue","partial":"creations/tongue"},
    {"bn":"ঘর","en":"House","partial":"creations/house"},
    {"bn":"পানি","en":"Water","partial":"creations/water"},
    {"bn":"বোধশক্তি / উপলব্ধি","en":"Understanding","partial":"creations/understanding"},
    {"bn":"তারা/নক্ষত্র","en":"Stars","partial":"creations/stars"},
    {"bn":"পোশাক","en":"Clothing","partial":"creations/clothing"},
    {"bn":"সিংহাসন","en":"Throne","partial":"creations/throne"},
    {"bn":"বিস্ফোরণ","en":"Blast","partial":"creations/blast"},
    {"bn":"জাতি","en":"Nation","partial":"creations/nation"},
    {"bn":"ধর্ম","en":"Religion","partial":"creations/religion"},
    {"bn":"পালঙ্ক","en":"Couch","partial":"creations/couch"},
    {"bn":"বসন্ত","en":"Springs","partial":"creations/springs"},
    {"bn":"জীবন","en":"Life","partial":"creations/life"},
    {"bn":"কঙ্কন","en":"Bracelet","partial":"creations/bracelet"},
    {"bn":"সৃষ্টি, সৃষ্টি শুরু হয় এবং পুনরাবৃত্তি","en":"Creation, Creation Begins And Repeated","partial":"creations/creation__creation_begins_and_repeated"},
    {"bn":"জলপাই","en":"Olive","partial":"creations/olive"},
    {"bn":"বীজ","en":"Seed","partial":"creations/seed"},
    {"bn":"কাদামাটি","en":"Clay","partial":"creations/clay"}
    ]
  },
  {
    id: "arabic-language",
    bn: "কুরআনের আরবি ভাষা",
    en: "Quranic Arabic Language",
    icon: "🔤",
    items: [
    {"bn":"আরবি ভাষা","en":"Arabic","partial":"arabic_languages/arabic"},
    {"bn":"শব্দ / পুনরাবৃত্তি","en":"Repeat","partial":"arabic_languages/repeat"},
    {"bn":"নাহু","en":"Nahu","partial":"arabic_languages/nahu"},
    {"bn":"ছরফ (সরফ)","en":"Sarf","partial":"arabic_languages/sarf"}
    ]
  },
  {
    id: "pillars",
    bn: "ইসলামের স্তম্ভ",
    en: "Pillars of Islam",
    icon: "🕌",
    items: [
    {"bn":"ঈমান / আকিদা / বিশ্বাস","en":"Iman Akida","partial":"pillars/iman_akida"},
    {"bn":"সলাত / নামায","en":"Salat","partial":"pillars/salat"},
    {"bn":"রোজা","en":"Sawm Fasting","partial":"pillars/sawm_fasting"},
    {"bn":"যাকাত","en":"Zakat","partial":"pillars/zakat"},
    {"bn":"হজ্ব","en":"Hajj","partial":"pillars/hajj"}
    ]
  },
  {
    id: "others",
    bn: "অন্যান্য",
    en: "Others",
    icon: "📋",
    items: [
    {"bn":"বিবিধ","en":"Miscellaneous","partial":"etc/dua"},
    {"bn":"আত্নশুদ্ধি/অন্তর/আখলাক","en":"Self-Purification / Heart / Akhlaq","partial":"etc/akhlakh_self_purification_heart"},
    {"bn":"ওয়াকফ নিয়মাবলী","en":"Waqf (Stop) Rules","partial":"stop_sign"},
    {"bn":"আরবি টাইপ করুন","en":"Arabic Keyboard Practice","partial":"arabic_keyboard"},
    {"bn":"কোরআন মুখস্ত যাচাই","en":"Quran Memorization Test","partial":"quran_memory_test"}
    ]
  }
];

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { LEGACY_MENU };
}
