/**
 * 99 Names of Allah (Asma ul Husna) Data
 * Standard list (Tirmidhi narration order), meanings in all 7 UI languages.
 * meanings.ar is a brief Arabic gloss of the name.
 *
 * Also: PROPHETS_25 — the 25 prophets named in the Quran (standard list).
 * Each `count` was computed from this repo's data/quran-tokens.json by
 * summing the name's token forms (incl. attached vocatives/prepositions,
 * e.g. يادم = "O Adam", وابرهيم = "and Ibrahim") and matches the
 * well-known published mention counts. `forms` lists those exact
 * normalized token spellings (Uthmani rasm, diacritics stripped) so the
 * app can find every occurrence at runtime. Where the bare spelling is
 * ambiguous (هود also = "Jews", صلح also = "righteous", يحيى also =
 * the verb "he lives"), the disambiguated verse list is stored in `refs`
 * instead. `ref` is the name's first occurrence (mushaf order).
 */

const NAMES_99 = [
  { n: 1, ar: "الرَّحْمَٰنُ", translit: "Ar-Raḥmān", meanings: { en: "The Most Merciful", bn: "পরম করুণাময়", fr: "Le Tout Miséricordieux", id: "Yang Maha Pengasih", ur: "نہایت مہربان", tr: "Çok Merhametli", ar: "واسع الرحمة" } },
  { n: 2, ar: "الرَّحِيمُ", translit: "Ar-Raḥīm", meanings: { en: "The Most Compassionate", bn: "অতি দয়ালু", fr: "Le Très Miséricordieux", id: "Yang Maha Penyayang", ur: "نہایت رحم والا", tr: "Çok Merhamet Eden", ar: "دائم الرحمة" } },
  { n: 3, ar: "الْمَلِكُ", translit: "Al-Malik", meanings: { en: "The King", bn: "সর্বাধিপতি", fr: "Le Souverain", id: "Yang Maha Merajai", ur: "بادشاہ", tr: "Mülkün Sahibi", ar: "الملك الحق" } },
  { n: 4, ar: "الْقُدُّوسُ", translit: "Al-Quddūs", meanings: { en: "The Most Holy", bn: "মহাপবিত্র", fr: "Le Très Saint", id: "Yang Maha Suci", ur: "نہایت پاک", tr: "Çok Kutsal", ar: "المنزه عن النقائص" } },
  { n: 5, ar: "السَّلَامُ", translit: "As-Salām", meanings: { en: "The Source of Peace", bn: "শান্তিদাতা", fr: "La Paix", id: "Yang Maha Sejahtera", ur: "سلامتی والا", tr: "Esenlik Veren", ar: "السالم من كل عيب" } },
  { n: 6, ar: "الْمُؤْمِنُ", translit: "Al-Mu'min", meanings: { en: "The Giver of Security", bn: "নিরাপত্তাদাতা", fr: "Le Rassurant", id: "Yang Maha Memberi Keamanan", ur: "امن دینے والا", tr: "Güven Veren", ar: "المؤمِّن لعباده" } },
  { n: 7, ar: "الْمُهَيْمِنُ", translit: "Al-Muhaymin", meanings: { en: "The Guardian", bn: "রক্ষণাবেক্ষণকারী", fr: "Le Protecteur", id: "Yang Maha Memelihara", ur: "نگہبان", tr: "Gözetip Koruyan", ar: "الرقيب الحافظ" } },
  { n: 8, ar: "الْعَزِيزُ", translit: "Al-ʿAzīz", meanings: { en: "The Almighty", bn: "মহাপরাক্রমশালী", fr: "Le Tout Puissant", id: "Yang Maha Perkasa", ur: "سب پر غالب", tr: "Mutlak Güç Sahibi", ar: "الغالب الذي لا يُقهر" } },
  { n: 9, ar: "الْجَبَّارُ", translit: "Al-Jabbār", meanings: { en: "The Compeller", bn: "মহাপ্রতাপশালী", fr: "Le Contraignant", id: "Yang Maha Gagah", ur: "زبردست", tr: "Dilediğini Yaptıran", ar: "الذي يجبر الخلق" } },
  { n: 10, ar: "الْمُتَكَبِّرُ", translit: "Al-Mutakabbir", meanings: { en: "The Supreme", bn: "মহাগৌরবান্বিত", fr: "Le Superbe", id: "Yang Maha Megah", ur: "بڑائی والا", tr: "Büyüklükte Eşsiz", ar: "المتعالي عن السوء" } },
  { n: 11, ar: "الْخَالِقُ", translit: "Al-Khāliq", meanings: { en: "The Creator", bn: "সৃষ্টিকর্তা", fr: "Le Créateur", id: "Yang Maha Pencipta", ur: "پیدا کرنے والا", tr: "Yaratan", ar: "الموجِد من العدم" } },
  { n: 12, ar: "الْبَارِئُ", translit: "Al-Bāri'", meanings: { en: "The Originator", bn: "নিখুঁত স্রষ্টা", fr: "Le Producteur", id: "Yang Maha Mengadakan", ur: "وجود بخشنے والا", tr: "Kusursuz Yaratan", ar: "الخالق بلا مثال" } },
  { n: 13, ar: "الْمُصَوِّرُ", translit: "Al-Muṣawwir", meanings: { en: "The Fashioner", bn: "আকৃতিদানকারী", fr: "Le Formateur", id: "Yang Maha Membentuk", ur: "صورت گر", tr: "Şekil Veren", ar: "المصوِّر للخلق" } },
  { n: 14, ar: "الْغَفَّارُ", translit: "Al-Ghaffār", meanings: { en: "The Ever-Forgiving", bn: "মহাক্ষমাশীল", fr: "Le Grand Pardonneur", id: "Yang Maha Pengampun", ur: "بہت بخشنے والا", tr: "Çok Bağışlayan", ar: "كثير المغفرة" } },
  { n: 15, ar: "الْقَهَّارُ", translit: "Al-Qahhār", meanings: { en: "The Subduer", bn: "মহাপরাক্রান্ত", fr: "Le Dominateur", id: "Yang Maha Menundukkan", ur: "سب پر قابو والا", tr: "Her Şeye Galip", ar: "القاهر فوق عباده" } },
  { n: 16, ar: "الْوَهَّابُ", translit: "Al-Wahhāb", meanings: { en: "The Bestower", bn: "মহাদাতা", fr: "Le Donateur", id: "Yang Maha Pemberi Karunia", ur: "بہت عطا کرنے والا", tr: "Karşılıksız Veren", ar: "كثير العطاء" } },
  { n: 17, ar: "الرَّزَّاقُ", translit: "Ar-Razzāq", meanings: { en: "The Provider", bn: "রিযিকদাতা", fr: "Le Pourvoyeur", id: "Yang Maha Pemberi Rezeki", ur: "رزق دینے والا", tr: "Rızık Veren", ar: "المتكفل بالرزق" } },
  { n: 18, ar: "الْفَتَّاحُ", translit: "Al-Fattāḥ", meanings: { en: "The Opener", bn: "মহাবিজয়দানকারী", fr: "Celui qui ouvre", id: "Yang Maha Pembuka", ur: "کھولنے والا", tr: "Kapıları Açan", ar: "الحاكم الفاتح" } },
  { n: 19, ar: "الْعَلِيمُ", translit: "Al-ʿAlīm", meanings: { en: "The All-Knowing", bn: "সর্বজ্ঞ", fr: "L'Omniscient", id: "Yang Maha Mengetahui", ur: "سب کچھ جاننے والا", tr: "Her Şeyi Bilen", ar: "المحيط علمه بكل شيء" } },
  { n: 20, ar: "الْقَابِضُ", translit: "Al-Qābiḍ", meanings: { en: "The Withholder", bn: "সংকোচনকারী", fr: "Celui qui rétracte", id: "Yang Maha Menyempitkan", ur: "تنگی دینے والا", tr: "Daraltan", ar: "القابض للأرزاق" } },
  { n: 21, ar: "الْبَاسِطُ", translit: "Al-Bāsiṭ", meanings: { en: "The Expander", bn: "সম্প্রসারণকারী", fr: "Celui qui étend", id: "Yang Maha Melapangkan", ur: "کشادگی دینے والا", tr: "Genişleten", ar: "الباسط للأرزاق" } },
  { n: 22, ar: "الْخَافِضُ", translit: "Al-Khāfiḍ", meanings: { en: "The Abaser", bn: "অবনতকারী", fr: "Celui qui abaisse", id: "Yang Maha Merendahkan", ur: "پست کرنے والا", tr: "Alçaltan", ar: "الخافض للجبابرة" } },
  { n: 23, ar: "الرَّافِعُ", translit: "Ar-Rāfiʿ", meanings: { en: "The Exalter", bn: "উন্নতকারী", fr: "Celui qui élève", id: "Yang Maha Meninggikan", ur: "بلند کرنے والا", tr: "Yücelten", ar: "الرافع لأوليائه" } },
  { n: 24, ar: "الْمُعِزُّ", translit: "Al-Muʿizz", meanings: { en: "The Giver of Honor", bn: "সম্মানদাতা", fr: "Celui qui honore", id: "Yang Maha Memuliakan", ur: "عزت دینے والا", tr: "İzzet Veren", ar: "المعطي العزة" } },
  { n: 25, ar: "الْمُذِلُّ", translit: "Al-Mudhill", meanings: { en: "The Humiliator", bn: "অপদস্থকারী", fr: "Celui qui humilie", id: "Yang Maha Menghinakan", ur: "ذلت دینے والا", tr: "Zillete Düşüren", ar: "المذل لأعدائه" } },
  { n: 26, ar: "السَّمِيعُ", translit: "As-Samīʿ", meanings: { en: "The All-Hearing", bn: "সর্বশ্রোতা", fr: "L'Audient", id: "Yang Maha Mendengar", ur: "سب کچھ سننے والا", tr: "Her Şeyi İşiten", ar: "السامع لكل شيء" } },
  { n: 27, ar: "الْبَصِيرُ", translit: "Al-Baṣīr", meanings: { en: "The All-Seeing", bn: "সর্বদ্রষ্টা", fr: "Le Clairvoyant", id: "Yang Maha Melihat", ur: "سب کچھ دیکھنے والا", tr: "Her Şeyi Gören", ar: "المبصر لكل شيء" } },
  { n: 28, ar: "الْحَكَمُ", translit: "Al-Ḥakam", meanings: { en: "The Judge", bn: "মহাবিচারক", fr: "L'Arbitre", id: "Yang Maha Menetapkan Hukum", ur: "فیصلہ کرنے والا", tr: "Hükmeden", ar: "الحاكم العدل" } },
  { n: 29, ar: "الْعَدْلُ", translit: "Al-ʿAdl", meanings: { en: "The Just", bn: "ন্যায়বিচারক", fr: "Le Juste", id: "Yang Maha Adil", ur: "عادل", tr: "Mutlak Adil", ar: "العادل في حكمه" } },
  { n: 30, ar: "اللَّطِيفُ", translit: "Al-Laṭīf", meanings: { en: "The Subtle One", bn: "সূক্ষ্মদর্শী", fr: "Le Doux", id: "Yang Maha Lembut", ur: "باریک بین مہربان", tr: "Lütufkâr", ar: "اللطيف بعباده" } },
  { n: 31, ar: "الْخَبِيرُ", translit: "Al-Khabīr", meanings: { en: "The All-Aware", bn: "সর্বজ্ঞাত", fr: "Le Bien-Informé", id: "Yang Maha Mengenal", ur: "خبردار", tr: "Her Şeyden Haberdar", ar: "العليم ببواطن الأمور" } },
  { n: 32, ar: "الْحَلِيمُ", translit: "Al-Ḥalīm", meanings: { en: "The Forbearing", bn: "মহাসহনশীল", fr: "Le Longanime", id: "Yang Maha Penyantun", ur: "بردبار", tr: "Çok Hoşgörülü", ar: "الذي لا يعجل بالعقوبة" } },
  { n: 33, ar: "الْعَظِيمُ", translit: "Al-ʿAẓīm", meanings: { en: "The Magnificent", bn: "মহান", fr: "Le Magnifique", id: "Yang Maha Agung", ur: "عظمت والا", tr: "Pek Yüce", ar: "العظيم في كل شيء" } },
  { n: 34, ar: "الْغَفُورُ", translit: "Al-Ghafūr", meanings: { en: "The All-Forgiving", bn: "ক্ষমাপরায়ণ", fr: "Le Pardonneur", id: "Yang Maha Pengampun", ur: "بخشنے والا", tr: "Bağışlayıcı", ar: "الساتر للذنوب" } },
  { n: 35, ar: "الشَّكُورُ", translit: "Ash-Shakūr", meanings: { en: "The Appreciative", bn: "গুণগ্রাহী", fr: "Le Reconnaissant", id: "Yang Maha Mensyukuri", ur: "قدر دان", tr: "Şükre Karşılık Veren", ar: "المجازي على القليل بالكثير" } },
  { n: 36, ar: "الْعَلِيُّ", translit: "Al-ʿAliyy", meanings: { en: "The Most High", bn: "সর্বোচ্চ", fr: "Le Très-Haut", id: "Yang Maha Tinggi", ur: "سب سے بلند", tr: "Pek Yüksek", ar: "العالي فوق خلقه" } },
  { n: 37, ar: "الْكَبِيرُ", translit: "Al-Kabīr", meanings: { en: "The Most Great", bn: "সুমহান", fr: "Le Très Grand", id: "Yang Maha Besar", ur: "سب سے بڑا", tr: "Pek Büyük", ar: "الكبير المتعال" } },
  { n: 38, ar: "الْحَفِيظُ", translit: "Al-Ḥafīẓ", meanings: { en: "The Preserver", bn: "মহারক্ষক", fr: "Le Gardien", id: "Yang Maha Menjaga", ur: "حفاظت کرنے والا", tr: "Koruyup Gözeten", ar: "الحافظ لكل شيء" } },
  { n: 39, ar: "الْمُقِيتُ", translit: "Al-Muqīt", meanings: { en: "The Sustainer", bn: "আহারদাতা", fr: "Le Nourricier", id: "Yang Maha Pemberi Kecukupan", ur: "روزی پہنچانے والا", tr: "Azık Veren", ar: "المتكفل بالأقوات" } },
  { n: 40, ar: "الْحَسِيبُ", translit: "Al-Ḥasīb", meanings: { en: "The Reckoner", bn: "মহাহিসাবগ্রহণকারী", fr: "Celui qui compte", id: "Yang Maha Membuat Perhitungan", ur: "حساب لینے والا", tr: "Hesaba Çeken", ar: "الكافي المحاسِب" } },
  { n: 41, ar: "الْجَلِيلُ", translit: "Al-Jalīl", meanings: { en: "The Majestic", bn: "মহামহিমান্বিত", fr: "Le Majestueux", id: "Yang Maha Luhur", ur: "بزرگی والا", tr: "Ululuk Sahibi", ar: "ذو الجلال والعظمة" } },
  { n: 42, ar: "الْكَرِيمُ", translit: "Al-Karīm", meanings: { en: "The Generous", bn: "মহাঅনুগ্রহশীল", fr: "Le Généreux", id: "Yang Maha Pemurah", ur: "کرم کرنے والا", tr: "Cömert", ar: "الجواد المعطي" } },
  { n: 43, ar: "الرَّقِيبُ", translit: "Ar-Raqīb", meanings: { en: "The Watchful", bn: "সদা পর্যবেক্ষক", fr: "Le Vigilant", id: "Yang Maha Mengawasi", ur: "نگران", tr: "Gözetleyen", ar: "المطّلع على كل شيء" } },
  { n: 44, ar: "الْمُجِيبُ", translit: "Al-Mujīb", meanings: { en: "The Responsive", bn: "দুআ কবুলকারী", fr: "Celui qui exauce", id: "Yang Maha Mengabulkan", ur: "دعا قبول کرنے والا", tr: "Duaları Kabul Eden", ar: "المجيب للدعاء" } },
  { n: 45, ar: "الْوَاسِعُ", translit: "Al-Wāsiʿ", meanings: { en: "The All-Encompassing", bn: "সর্বব্যাপী", fr: "L'Ample", id: "Yang Maha Luas", ur: "وسعت والا", tr: "İlmi ve Rahmeti Geniş", ar: "الواسع الغني" } },
  { n: 46, ar: "الْحَكِيمُ", translit: "Al-Ḥakīm", meanings: { en: "The All-Wise", bn: "মহাপ্রজ্ঞাময়", fr: "Le Sage", id: "Yang Maha Bijaksana", ur: "حکمت والا", tr: "Hikmet Sahibi", ar: "الحكيم في تدبيره" } },
  { n: 47, ar: "الْوَدُودُ", translit: "Al-Wadūd", meanings: { en: "The Loving", bn: "প্রেমময়", fr: "L'Aimant", id: "Yang Maha Mengasihi", ur: "محبت کرنے والا", tr: "Çok Seven", ar: "المحب لعباده" } },
  { n: 48, ar: "الْمَجِيدُ", translit: "Al-Majīd", meanings: { en: "The Glorious", bn: "মহাগৌরবময়", fr: "Le Glorieux", id: "Yang Maha Mulia", ur: "بزرگ شان والا", tr: "Şanı Yüce", ar: "العظيم الشأن" } },
  { n: 49, ar: "الْبَاعِثُ", translit: "Al-Bāʿith", meanings: { en: "The Resurrector", bn: "পুনরুত্থানকারী", fr: "Celui qui ressuscite", id: "Yang Maha Membangkitkan", ur: "اٹھانے والا", tr: "Dirilten", ar: "الباعث بعد الموت" } },
  { n: 50, ar: "الشَّهِيدُ", translit: "Ash-Shahīd", meanings: { en: "The Witness", bn: "সর্বসাক্ষী", fr: "Le Témoin", id: "Yang Maha Menyaksikan", ur: "گواہ", tr: "Her Şeye Şahit", ar: "الشاهد على كل شيء" } },
  { n: 51, ar: "الْحَقُّ", translit: "Al-Ḥaqq", meanings: { en: "The Truth", bn: "চিরসত্য", fr: "Le Vrai", id: "Yang Maha Benar", ur: "برحق", tr: "Gerçeğin Kendisi", ar: "الثابت الذي لا يزول" } },
  { n: 52, ar: "الْوَكِيلُ", translit: "Al-Wakīl", meanings: { en: "The Trustee", bn: "মহানির্ভরযোগ্য", fr: "Le Garant", id: "Yang Maha Mewakili", ur: "کارساز", tr: "Güvenilir Vekil", ar: "المتكفل بأمور عباده" } },
  { n: 53, ar: "الْقَوِيُّ", translit: "Al-Qawiyy", meanings: { en: "The All-Strong", bn: "মহাশক্তিধর", fr: "Le Fort", id: "Yang Maha Kuat", ur: "بڑی قوت والا", tr: "Pek Güçlü", ar: "صاحب القوة التامة" } },
  { n: 54, ar: "الْمَتِينُ", translit: "Al-Matīn", meanings: { en: "The Firm", bn: "সুদৃঢ়", fr: "L'Inébranlable", id: "Yang Maha Kokoh", ur: "مضبوط", tr: "Sarsılmaz Güç Sahibi", ar: "الشديد القوي" } },
  { n: 55, ar: "الْوَلِيُّ", translit: "Al-Waliyy", meanings: { en: "The Protecting Friend", bn: "অভিভাবক", fr: "L'Allié", id: "Yang Maha Melindungi", ur: "دوست و مددگار", tr: "Dost ve Yardımcı", ar: "الناصر المتولي" } },
  { n: 56, ar: "الْحَمِيدُ", translit: "Al-Ḥamīd", meanings: { en: "The Praiseworthy", bn: "সর্বপ্রশংসিত", fr: "Le Digne de louange", id: "Yang Maha Terpuji", ur: "تعریف کے لائق", tr: "Övgüye Lâyık", ar: "المستحق للحمد" } },
  { n: 57, ar: "الْمُحْصِي", translit: "Al-Muḥṣī", meanings: { en: "The Enumerator", bn: "সর্বগণনাকারী", fr: "Celui qui dénombre", id: "Yang Maha Menghitung", ur: "شمار کرنے والا", tr: "Her Şeyi Sayan", ar: "المحصي لكل شيء" } },
  { n: 58, ar: "الْمُبْدِئُ", translit: "Al-Mubdi'", meanings: { en: "The Initiator", bn: "সূচনাকারী", fr: "Celui qui commence", id: "Yang Maha Memulai", ur: "پہلی بار پیدا کرنے والا", tr: "İlkin Yaratan", ar: "المبدئ للخلق" } },
  { n: 59, ar: "الْمُعِيدُ", translit: "Al-Muʿīd", meanings: { en: "The Restorer", bn: "পুনঃসৃষ্টিকারী", fr: "Celui qui redonne", id: "Yang Maha Mengembalikan", ur: "دوبارہ پیدا کرنے والا", tr: "Yeniden Dirilten", ar: "المعيد للخلق" } },
  { n: 60, ar: "الْمُحْيِي", translit: "Al-Muḥyī", meanings: { en: "The Giver of Life", bn: "জীবনদাতা", fr: "Celui qui fait vivre", id: "Yang Maha Menghidupkan", ur: "زندگی دینے والا", tr: "Hayat Veren", ar: "المحيي للخلق" } },
  { n: 61, ar: "الْمُمِيتُ", translit: "Al-Mumīt", meanings: { en: "The Bringer of Death", bn: "মৃত্যুদাতা", fr: "Celui qui fait mourir", id: "Yang Maha Mematikan", ur: "موت دینے والا", tr: "Öldüren", ar: "المميت للأحياء" } },
  { n: 62, ar: "الْحَيُّ", translit: "Al-Ḥayy", meanings: { en: "The Ever-Living", bn: "চিরঞ্জীব", fr: "Le Vivant", id: "Yang Maha Hidup", ur: "ہمیشہ زندہ", tr: "Diri Olan", ar: "الحي الذي لا يموت" } },
  { n: 63, ar: "الْقَيُّومُ", translit: "Al-Qayyūm", meanings: { en: "The Sustainer of All", bn: "চিরপ্রতিষ্ঠিত", fr: "L'Immuable", id: "Yang Maha Berdiri Sendiri", ur: "سب کو قائم رکھنے والا", tr: "Her Şeyi Ayakta Tutan", ar: "القائم على كل شيء" } },
  { n: 64, ar: "الْوَاجِدُ", translit: "Al-Wājid", meanings: { en: "The Finder", bn: "সর্বপ্রাপক", fr: "Celui qui trouve", id: "Yang Maha Menemukan", ur: "پانے والا", tr: "Dilediğini Bulan", ar: "الغني الذي لا يفتقر" } },
  { n: 65, ar: "الْمَاجِدُ", translit: "Al-Mājid", meanings: { en: "The Noble", bn: "মহিমান্বিত", fr: "Le Noble", id: "Yang Maha Mulia Sifatnya", ur: "بزرگی والا", tr: "Şerefi Yüce", ar: "الماجد الكريم" } },
  { n: 66, ar: "الْوَاحِدُ", translit: "Al-Wāḥid", meanings: { en: "The One", bn: "একক", fr: "L'Unique", id: "Yang Maha Esa", ur: "یکتا", tr: "Tek Olan", ar: "الواحد بلا شريك" } },
  { n: 67, ar: "الْأَحَدُ", translit: "Al-Aḥad", meanings: { en: "The Indivisible One", bn: "অদ্বিতীয়", fr: "L'Un", id: "Yang Maha Tunggal", ur: "اکیلا", tr: "Bir Olan", ar: "الأحد الفرد" } },
  { n: 68, ar: "الصَّمَدُ", translit: "Aṣ-Ṣamad", meanings: { en: "The Eternal Refuge", bn: "অমুখাপেক্ষী", fr: "L'Absolu", id: "Yang Maha Dibutuhkan", ur: "بے نیاز", tr: "Her Şey O'na Muhtaç", ar: "المقصود في الحوائج" } },
  { n: 69, ar: "الْقَادِرُ", translit: "Al-Qādir", meanings: { en: "The Capable", bn: "সর্বশক্তিমান", fr: "Le Puissant", id: "Yang Maha Kuasa", ur: "قدرت والا", tr: "Kudret Sahibi", ar: "القادر على كل شيء" } },
  { n: 70, ar: "الْمُقْتَدِرُ", translit: "Al-Muqtadir", meanings: { en: "The Omnipotent", bn: "মহাক্ষমতাবান", fr: "Le Tout-Puissant", id: "Yang Maha Berkuasa", ur: "بڑی قدرت والا", tr: "Mutlak Kudret Sahibi", ar: "التام القدرة" } },
  { n: 71, ar: "الْمُقَدِّمُ", translit: "Al-Muqaddim", meanings: { en: "The Expediter", bn: "অগ্রসরকারী", fr: "Celui qui avance", id: "Yang Maha Mendahulukan", ur: "آگے کرنے والا", tr: "Öne Alan", ar: "المقدِّم لما يشاء" } },
  { n: 72, ar: "الْمُؤَخِّرُ", translit: "Al-Mu'akhkhir", meanings: { en: "The Delayer", bn: "বিলম্বকারী", fr: "Celui qui recule", id: "Yang Maha Mengakhirkan", ur: "پیچھے کرنے والا", tr: "Geriye Bırakan", ar: "المؤخِّر لما يشاء" } },
  { n: 73, ar: "الْأَوَّلُ", translit: "Al-Awwal", meanings: { en: "The First", bn: "সর্বপ্রথম", fr: "Le Premier", id: "Yang Maha Awal", ur: "سب سے پہلا", tr: "İlk", ar: "الأول بلا بداية" } },
  { n: 74, ar: "الْآخِرُ", translit: "Al-Ākhir", meanings: { en: "The Last", bn: "সর্বশেষ", fr: "Le Dernier", id: "Yang Maha Akhir", ur: "سب سے آخر", tr: "Son", ar: "الآخر بلا نهاية" } },
  { n: 75, ar: "الظَّاهِرُ", translit: "Aẓ-Ẓāhir", meanings: { en: "The Manifest", bn: "প্রকাশ্য", fr: "L'Apparent", id: "Yang Maha Nyata", ur: "ظاہر", tr: "Aşikâr Olan", ar: "الظاهر فوق كل شيء" } },
  { n: 76, ar: "الْبَاطِنُ", translit: "Al-Bāṭin", meanings: { en: "The Hidden", bn: "গুপ্ত", fr: "Le Caché", id: "Yang Maha Tersembunyi", ur: "پوشیدہ", tr: "Gizli Olan", ar: "العالم بالخفايا" } },
  { n: 77, ar: "الْوَالِي", translit: "Al-Wālī", meanings: { en: "The Governor", bn: "মহাপরিচালক", fr: "Le Gérant", id: "Yang Maha Memerintah", ur: "حاکم و والی", tr: "İşleri Yöneten", ar: "المتولي للأمور" } },
  { n: 78, ar: "الْمُتَعَالِي", translit: "Al-Mutaʿālī", meanings: { en: "The Most Exalted", bn: "সর্বোন্নত", fr: "Le Sublime", id: "Yang Maha Tinggi Derajat", ur: "سب سے برتر", tr: "Pek Yüce Olan", ar: "المتعالي عن النقائص" } },
  { n: 79, ar: "الْبَرُّ", translit: "Al-Barr", meanings: { en: "The Source of Goodness", bn: "পরম উপকারী", fr: "Le Bon", id: "Yang Maha Baik", ur: "نیکی والا", tr: "İyilik Sahibi", ar: "كثير الإحسان" } },
  { n: 80, ar: "التَّوَّابُ", translit: "At-Tawwāb", meanings: { en: "The Acceptor of Repentance", bn: "তাওবা কবুলকারী", fr: "L'Accueillant au repentir", id: "Yang Maha Penerima Tobat", ur: "توبہ قبول کرنے والا", tr: "Tövbeleri Kabul Eden", ar: "القابل للتوبة" } },
  { n: 81, ar: "الْمُنْتَقِمُ", translit: "Al-Muntaqim", meanings: { en: "The Avenger", bn: "প্রতিশোধগ্রহণকারী", fr: "Le Vengeur", id: "Yang Maha Pembalas", ur: "بدلہ لینے والا", tr: "Suçluları Cezalandıran", ar: "المنتقم من العصاة" } },
  { n: 82, ar: "الْعَفُوُّ", translit: "Al-ʿAfuww", meanings: { en: "The Pardoner", bn: "মহাক্ষমাকারী", fr: "L'Indulgent", id: "Yang Maha Pemaaf", ur: "بہت معاف کرنے والا", tr: "Affedici", ar: "كثير العفو" } },
  { n: 83, ar: "الرَّءُوفُ", translit: "Ar-Ra'ūf", meanings: { en: "The Most Kind", bn: "পরম স্নেহশীল", fr: "Le Compatissant", id: "Yang Maha Belas Kasih", ur: "نہایت شفیق", tr: "Çok Şefkatli", ar: "الرؤوف بعباده" } },
  { n: 84, ar: "مَالِكُ الْمُلْكِ", translit: "Mālik-ul-Mulk", meanings: { en: "Master of the Kingdom", bn: "রাজত্বের মালিক", fr: "Maître du Royaume", id: "Pemilik Kerajaan", ur: "ملک کا مالک", tr: "Mülkün Ebedî Sahibi", ar: "مالك الملك كله" } },
  { n: 85, ar: "ذُو الْجَلَالِ وَالْإِكْرَامِ", translit: "Dhul-Jalāli wal-Ikrām", meanings: { en: "Lord of Majesty and Honor", bn: "মহিমা ও সম্মানের অধিকারী", fr: "Détenteur de Majesté et de Générosité", id: "Pemilik Kebesaran dan Kemuliaan", ur: "جلال اور اکرام والا", tr: "Azamet ve İkram Sahibi", ar: "صاحب الجلال والإكرام" } },
  { n: 86, ar: "الْمُقْسِطُ", translit: "Al-Muqsiṭ", meanings: { en: "The Equitable", bn: "ন্যায়পরায়ণ", fr: "L'Équitable", id: "Yang Maha Memberi Keadilan", ur: "انصاف کرنے والا", tr: "Adaletle Hükmeden", ar: "العادل المنصف" } },
  { n: 87, ar: "الْجَامِعُ", translit: "Al-Jāmiʿ", meanings: { en: "The Gatherer", bn: "একত্রকারী", fr: "Le Rassembleur", id: "Yang Maha Mengumpulkan", ur: "جمع کرنے والا", tr: "Toplayan", ar: "الجامع للخلق يوم القيامة" } },
  { n: 88, ar: "الْغَنِيُّ", translit: "Al-Ghaniyy", meanings: { en: "The Self-Sufficient", bn: "অভাবমুক্ত", fr: "Le Riche", id: "Yang Maha Kaya", ur: "غنی", tr: "Zengin, Muhtaç Olmayan", ar: "الغني عن الخلق" } },
  { n: 89, ar: "الْمُغْنِي", translit: "Al-Mughnī", meanings: { en: "The Enricher", bn: "অভাবমোচনকারী", fr: "Celui qui enrichit", id: "Yang Maha Memberi Kekayaan", ur: "غنی کرنے والا", tr: "Zenginlik Veren", ar: "المغني لعباده" } },
  { n: 90, ar: "الْمَانِعُ", translit: "Al-Māniʿ", meanings: { en: "The Preventer", bn: "প্রতিরোধকারী", fr: "Celui qui empêche", id: "Yang Maha Mencegah", ur: "روکنے والا", tr: "Engelleyen", ar: "المانع لما يشاء" } },
  { n: 91, ar: "الضَّارُّ", translit: "Aḍ-Ḍārr", meanings: { en: "The Distresser", bn: "ক্ষতি সাধনকারী", fr: "Celui qui peut nuire", id: "Yang Maha Pemberi Mudarat", ur: "نقصان پہنچانے والا", tr: "Zarar Vermeye Kâdir", ar: "الضار بحكمته" } },
  { n: 92, ar: "النَّافِعُ", translit: "An-Nāfiʿ", meanings: { en: "The Benefiter", bn: "কল্যাণকারী", fr: "Le Bienfaisant", id: "Yang Maha Pemberi Manfaat", ur: "نفع دینے والا", tr: "Fayda Veren", ar: "النافع بفضله" } },
  { n: 93, ar: "النُّورُ", translit: "An-Nūr", meanings: { en: "The Light", bn: "মহাজ্যোতি", fr: "La Lumière", id: "Yang Maha Bercahaya", ur: "نور", tr: "Nûr", ar: "نور السماوات والأرض" } },
  { n: 94, ar: "الْهَادِي", translit: "Al-Hādī", meanings: { en: "The Guide", bn: "পথপ্রদর্শক", fr: "Le Guide", id: "Yang Maha Pemberi Petunjuk", ur: "ہدایت دینے والا", tr: "Hidayet Veren", ar: "الهادي إلى الحق" } },
  { n: 95, ar: "الْبَدِيعُ", translit: "Al-Badīʿ", meanings: { en: "The Incomparable Originator", bn: "অভিনব স্রষ্টা", fr: "L'Inventeur", id: "Yang Maha Pencipta Tanpa Contoh", ur: "بے مثال پیدا کرنے والا", tr: "Örneksiz Yaratan", ar: "المبدع بلا مثال" } },
  { n: 96, ar: "الْبَاقِي", translit: "Al-Bāqī", meanings: { en: "The Everlasting", bn: "চিরস্থায়ী", fr: "Le Permanent", id: "Yang Maha Kekal", ur: "ہمیشہ باقی رہنے والا", tr: "Bâki Olan", ar: "الباقي بعد فناء الخلق" } },
  { n: 97, ar: "الْوَارِثُ", translit: "Al-Wārith", meanings: { en: "The Inheritor", bn: "চূড়ান্ত উত্তরাধিকারী", fr: "L'Héritier", id: "Yang Maha Mewarisi", ur: "سب کا وارث", tr: "Her Şeyin Vârisi", ar: "الوارث بعد فناء الخلق" } },
  { n: 98, ar: "الرَّشِيدُ", translit: "Ar-Rashīd", meanings: { en: "The Guide to the Right Path", bn: "সঠিক পথের নির্দেশক", fr: "Le Guide Parfait", id: "Yang Maha Pandai", ur: "رہنمائی کرنے والا", tr: "Doğru Yolu Gösteren", ar: "المرشد إلى الصواب" } },
  { n: 99, ar: "الصَّبُورُ", translit: "Aṣ-Ṣabūr", meanings: { en: "The Most Patient", bn: "মহাধৈর্যশীল", fr: "Le Très Patient", id: "Yang Maha Sabar", ur: "بڑا صابر", tr: "Çok Sabırlı", ar: "الذي لا يعاجل بالعقوبة" } }
];

const PROPHETS_25 = [
  { n: 1, ar: "آدَم", translit: "Ādam", names: { en: "Adam", bn: "আদম", fr: "Adam", id: "Adam", ur: "آدم", tr: "Âdem", ar: "آدم" }, count: 25, ref: "2:31", forms: ["ءادم", "يادم", "لءادم", "ويادم"] },
  { n: 2, ar: "إِدْرِيس", translit: "Idrīs", names: { en: "Idris (Enoch)", bn: "ইদরীস", fr: "Idris (Hénoch)", id: "Idris", ur: "ادریس", tr: "İdris", ar: "إدريس" }, count: 2, ref: "19:56", forms: ["ادريس", "وادريس"] },
  { n: 3, ar: "نُوح", translit: "Nūḥ", names: { en: "Noah", bn: "নূহ", fr: "Noé", id: "Nuh", ur: "نوح", tr: "Nûh", ar: "نوح" }, count: 43, ref: "3:33", forms: ["نوح", "نوحا", "ونوحا", "ينوح"] },
  { n: 4, ar: "هُود", translit: "Hūd", names: { en: "Hud", bn: "হূদ", fr: "Houd", id: "Hud", ur: "ہود", tr: "Hûd", ar: "هود" }, count: 7, ref: "7:65", refs: ["7:65", "11:50", "11:53", "11:58", "11:60", "11:89", "26:124"] },
  { n: 5, ar: "صَالِح", translit: "Ṣāliḥ", names: { en: "Salih", bn: "সালিহ", fr: "Salih", id: "Shaleh", ur: "صالح", tr: "Salih", ar: "صالح" }, count: 9, ref: "7:73", refs: ["7:73", "7:75", "7:77", "11:61", "11:62", "11:66", "11:89", "26:142", "27:45"] },
  { n: 6, ar: "إِبْرَاهِيم", translit: "Ibrāhīm", names: { en: "Abraham", bn: "ইবরাহীম", fr: "Abraham", id: "Ibrahim", ur: "ابراہیم", tr: "İbrahim", ar: "إبراهيم" }, count: 69, ref: "2:124", forms: ["ابرهيم", "ابرهم", "بابرهيم", "يابرهيم", "لابرهيم", "وابرهيم"] },
  { n: 7, ar: "لُوط", translit: "Lūṭ", names: { en: "Lot", bn: "লূত", fr: "Loth", id: "Luth", ur: "لوط", tr: "Lût", ar: "لوط" }, count: 27, ref: "6:86", forms: ["لوط", "لوطا", "ولوطا", "يلوط"] },
  { n: 8, ar: "إِسْمَاعِيل", translit: "Ismāʿīl", names: { en: "Ishmael", bn: "ইসমাঈল", fr: "Ismaël", id: "Ismail", ur: "اسماعیل", tr: "İsmail", ar: "إسماعيل" }, count: 12, ref: "2:125", forms: ["اسمعيل", "واسمعيل"] },
  { n: 9, ar: "إِسْحَاق", translit: "Isḥāq", names: { en: "Isaac", bn: "ইসহাক", fr: "Isaac", id: "Ishaq", ur: "اسحاق", tr: "İshak", ar: "إسحاق" }, count: 17, ref: "2:133", forms: ["اسحق", "واسحق", "باسحق"] },
  { n: 10, ar: "يَعْقُوب", translit: "Yaʿqūb", names: { en: "Jacob", bn: "ইয়াকুব", fr: "Jacob", id: "Ya'qub", ur: "یعقوب", tr: "Yakub", ar: "يعقوب" }, count: 16, ref: "2:132", forms: ["يعقوب", "ويعقوب"] },
  { n: 11, ar: "يُوسُف", translit: "Yūsuf", names: { en: "Joseph", bn: "ইউসুফ", fr: "Joseph", id: "Yusuf", ur: "یوسف", tr: "Yusuf", ar: "يوسف" }, count: 27, ref: "6:84", forms: ["يوسف", "ويوسف", "ليوسف", "بيوسف"] },
  { n: 12, ar: "أَيُّوب", translit: "Ayyūb", names: { en: "Job", bn: "আইয়ুব", fr: "Job", id: "Ayyub", ur: "ایوب", tr: "Eyyûb", ar: "أيوب" }, count: 4, ref: "4:163", forms: ["ايوب", "وايوب"] },
  { n: 13, ar: "ذُو الْكِفْل", translit: "Dhul-Kifl", names: { en: "Dhul-Kifl", bn: "যুলকিফল", fr: "Dhoul-Kifl", id: "Zulkifli", ur: "ذوالکفل", tr: "Zülkifl", ar: "ذو الكفل" }, count: 2, ref: "21:85", refs: ["21:85", "38:48"] },
  { n: 14, ar: "شُعَيْب", translit: "Shuʿayb", names: { en: "Shuayb", bn: "শুআইব", fr: "Chouaïb", id: "Syu'aib", ur: "شعیب", tr: "Şuayb", ar: "شعيب" }, count: 11, ref: "7:85", forms: ["شعيب", "شعيبا", "يشعيب"] },
  { n: 15, ar: "مُوسَىٰ", translit: "Mūsā", names: { en: "Moses", bn: "মূসা", fr: "Moïse", id: "Musa", ur: "موسیٰ", tr: "Musa", ar: "موسى" }, count: 136, ref: "2:51", forms: ["موسى", "يموسى", "وموسى", "بموسى", "لموسى"] },
  { n: 16, ar: "هَارُون", translit: "Hārūn", names: { en: "Aaron", bn: "হারূন", fr: "Aaron", id: "Harun", ur: "ہارون", tr: "Harun", ar: "هارون" }, count: 20, ref: "2:248", forms: ["هرون", "وهرون", "يهرون"] },
  { n: 17, ar: "دَاوُود", translit: "Dāwūd", names: { en: "David", bn: "দাঊদ", fr: "David", id: "Daud", ur: "داؤد", tr: "Davud", ar: "داوود" }, count: 16, ref: "2:251", forms: ["داود", "وداود", "يداود", "لداود"] },
  { n: 18, ar: "سُلَيْمَان", translit: "Sulaymān", names: { en: "Solomon", bn: "সুলাইমান", fr: "Salomon", id: "Sulaiman", ur: "سلیمان", tr: "Süleyman", ar: "سليمان" }, count: 17, ref: "2:102", forms: ["سليمن", "وسليمن", "لسليمن", "ولسليمن"] },
  { n: 19, ar: "إِلْيَاس", translit: "Ilyās", names: { en: "Elijah", bn: "ইলিয়াস", fr: "Élie", id: "Ilyas", ur: "الیاس", tr: "İlyas", ar: "إلياس" }, count: 2, ref: "6:85", refs: ["6:85", "37:123"] },
  { n: 20, ar: "الْيَسَع", translit: "Al-Yasaʿ", names: { en: "Elisha", bn: "আল-ইয়াসা", fr: "Élisée", id: "Ilyasa", ur: "الیسع", tr: "Elyesa", ar: "اليسع" }, count: 2, ref: "6:86", forms: ["واليسع"] },
  { n: 21, ar: "يُونُس", translit: "Yūnus", names: { en: "Jonah", bn: "ইউনুস", fr: "Jonas", id: "Yunus", ur: "یونس", tr: "Yunus", ar: "يونس" }, count: 4, ref: "4:163", forms: ["يونس", "ويونس"] },
  { n: 22, ar: "زَكَرِيَّا", translit: "Zakariyyā", names: { en: "Zechariah", bn: "যাকারিয়া", fr: "Zacharie", id: "Zakaria", ur: "زکریا", tr: "Zekeriya", ar: "زكريا" }, count: 7, ref: "3:37", forms: ["زكريا", "وزكريا", "يزكريا"] },
  { n: 23, ar: "يَحْيَىٰ", translit: "Yaḥyā", names: { en: "John", bn: "ইয়াহইয়া", fr: "Jean", id: "Yahya", ur: "یحییٰ", tr: "Yahya", ar: "يحيى" }, count: 5, ref: "3:39", refs: ["3:39", "6:85", "19:7", "19:12", "21:90"] },
  { n: 24, ar: "عِيسَىٰ", translit: "ʿĪsā", names: { en: "Jesus", bn: "ঈসা", fr: "Jésus", id: "Isa", ur: "عیسیٰ", tr: "İsa", ar: "عيسى" }, count: 25, ref: "2:87", forms: ["عيسى", "وعيسى", "يعيسى", "بعيسى"] },
  { n: 25, ar: "مُحَمَّد", translit: "Muḥammad", names: { en: "Muhammad", bn: "মুহাম্মাদ", fr: "Muhammad", id: "Muhammad", ur: "محمد", tr: "Muhammed", ar: "محمد" }, count: 4, ref: "3:144", forms: ["محمد"] }
];

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { NAMES_99, PROPHETS_25 };
}
