/**
 * Resources — a curated hub of trusted external Quran-study websites, grouped by
 * category. Every link was verified live and vetted for reputability (see
 * docs/resources-2026-07-14.md). Descriptions are bilingual (en + bn); other UI
 * languages fall back to English. Renders into #resources-container (tab
 * "resources"). Links open in a new tab.
 */

const RESOURCES_DATA = [
  { id: 'study', emoji: '📖', titleKey: 'resources_cat_study', items: [
    { name: 'Quran.com', url: 'https://quran.com', emoji: '📖',
      en: 'Free reader: translations, word-by-word, tafsir, audio', bn: 'ফ্রি রিডার: অনুবাদ, শব্দে-শব্দে, তাফসির ও তিলাওয়াত', zh: 'Free reader: translations, word-by-word, tafsir, audio', ja: 'Free reader: translations, word-by-word, tafsir, audio'},
    { name: 'QuranWBW', url: 'https://quranwbw.com', emoji: '📝',
      en: 'Word-by-word meaning, transliteration, morphology, word audio', bn: 'শব্দে-শব্দে অর্থ, উচ্চারণ, রূপতত্ত্ব ও শব্দ-অডিও', zh: 'Word-by-word meaning, transliteration, morphology, word audio', ja: 'Word-by-word meaning, transliteration, morphology, word audio'},
    { name: 'Greentech Al Quran', url: 'https://gtaf.org/apps/quran/', emoji: '📲',
      en: 'Word-by-word, tafsir & mushaf in 60+ languages (Bangla)', bn: '৬০+ ভাষায় শব্দে-শব্দে, তাফসির ও মুসহাফ (বাংলাসহ)', zh: 'Word-by-word, tafsir & mushaf in 60+ languages (Bangla)', ja: 'Word-by-word, tafsir & mushaf in 60+ languages (Bangla)'},
    { name: 'Quranflash', url: 'https://app.quranflash.com', emoji: '📄',
      en: 'Interactive mushaf reader with many print editions', bn: 'অনেক ছাপার সংস্করণসহ ইন্টারেক্টিভ মুসহাফ পাঠক'},
    { name: 'Al-Quran.info', url: 'https://al-quran.info', emoji: '🌐',
      en: 'Multi-language translations, tafsir, root & word search', bn: 'বহুভাষিক অনুবাদ, তাফসির ও মূল-শব্দ অনুসন্ধান', zh: 'Multi-language translations, tafsir, root & word search', ja: 'Multi-language translations, tafsir, root & word search'},
    { name: 'KSU Ayat', url: 'https://quran.ksu.edu.sa', emoji: '🎧',
      en: 'University mushaf: tajweed colours, reciters, tafsir', bn: 'বিশ্ববিদ্যালয়ের মুসহাফ: তাজবিদ রঙ, কারি ও তাফসির', zh: 'University mushaf: tajweed colours, reciters, tafsir', ja: 'University mushaf: tajweed colours, reciters, tafsir'},
    { name: 'Quran 12-21', url: 'https://quran12-21.org/en', emoji: '🏛️',
      en: 'Academic parallel corpus of Quran translations in Europe', bn: 'ইউরোপে কুরআন অনুবাদের একাডেমিক সমান্তরাল সংগ্রহ', zh: 'Academic parallel corpus of Quran translations in Europe', ja: 'Academic parallel corpus of Quran translations in Europe'},
    { name: 'QuranReflect', url: 'https://quranreflect.com', emoji: '💭',
      en: 'Community platform for reflections & tadabbur on verses', bn: 'আয়াত নিয়ে তাদাব্বুর ও চিন্তার কমিউনিটি প্ল্যাটফর্ম'},
    { name: 'Quran Index', url: 'https://quranindex.info', emoji: '🗂️',
      en: '900+ topic index, translations, reciters, downloads', bn: '৯০০+ বিষয়ভিত্তিক কুরআন সূচি ও অনুবাদ', zh: '900+ topic index, translations, reciters, downloads', ja: '900+ topic index, translations, reciters, downloads'},
    { name: 'IslamiCity Quran Search', url: 'https://www.islamicity.org/quransearch/', emoji: '🔎',
      en: 'Search Quran by topic, word, phrase or root', bn: 'বিষয়/শব্দ/মূল ধরে কুরআন অনুসন্ধান'},
    { name: 'Quran Analysis', url: 'http://qurananalysis.com/analysis/', emoji: '📊',
      en: 'Quran word frequency, concordance & statistics tool', bn: 'কুরআন শব্দ পরিসংখ্যান ও কনকর্ড্যান্স টুল', zh: 'Quran word frequency, concordance & statistics tool', ja: 'Quran word frequency, concordance & statistics tool'},
    { name: 'IslamHouse Translations', url: 'https://quran.islamhouse.com/en/', emoji: '🌍',
      en: 'Quran translations in 100+ languages, free', bn: '১০০+ ভাষায় কুরআন অনুবাদ বিনামূল্যে', zh: 'Quran translations in 100+ languages, free', ja: 'Quran translations in 100+ languages, free'},
    { name: 'Quran Kemenag (Indonesia)', url: 'https://quran.kemenag.go.id', emoji: '🇮🇩',
      en: "Indonesia's official Quran portal: translation & tafsir", bn: 'ইন্দোনেশিয়ার সরকারি কুরআন পোর্টাল ও তাফসির' },
    { name: 'Diyanet Kuran (Turkey)', url: 'https://kuran.diyanet.gov.tr', emoji: '🇹🇷',
      en: "Turkey's official Diyanet Quran portal: translation, audio", bn: 'তুরস্কের সরকারি কুরআন পোর্টাল ও অনুবাদ' },
    { name: 'Al-Aqidah al-Tahawiyyah', url: 'https://www.abuaminaelias.com/aqeedah-tahawiyyah/', emoji: '☝️',
      en: 'Tahawi creed text with English translation', bn: 'তাহাবি আকিদা মূল পাঠ ও ইংরেজি অনুবাদ'},
    { name: 'Quran Mind Maps', url: 'https://practicalislam.online/the-holy-quran/quranic-flow-chart/', emoji: '🗺️',
      en: 'Free mind-maps of surah themes and structure', bn: 'সূরার থিম ও কাঠামোর ফ্রি মাইন্ড-ম্যাপ'},
    { name: 'Ulum al-Quran (SunnahOnline)', url: 'https://sunnahonline.com/library/the-majestic-quran/184-an-introduction-to-ulum-al-quran', emoji: '🔬',
      en: 'Free introduction to the sciences of the Quran', bn: 'উলূমুল কুরআন—কুরআন বিজ্ঞানের ফ্রি পরিচিতি'},
    { name: 'Learn Salah (Masjid ar-Rahmah)', url: 'https://www.mymasjid.ca/beginners-guide-learn-pray-salah/', emoji: '🕌',
      en: 'Step-by-step salah & wudu guide for beginners', bn: 'শুরুকারীদের জন্য ধাপে ধাপে নামাজ ও অজুর গাইড'},
    { name: 'Islam By Touch (Braille)', url: 'https://www.islambytouch.com', emoji: '🦯',
      en: 'Free Braille Quran for the blind community', bn: 'অন্ধদের জন্য বিনামূল্যে ব্রেইল কুরআন'},
    { name: 'Quran Majeed', url: 'https://pakdata.com/products/quran-majeed/', emoji: '📱',
      en: 'Popular free Quran app: recitations and translations', bn: 'জনপ্রিয় ফ্রি কুরআন অ্যাপ, তিলাওয়াত ও অনুবাদ'},
    { name: 'King Fahd Quran Complex', url: 'https://qurancomplex.gov.sa/en/', emoji: '📗',
      en: 'Official Madinah Mushaf editions & riwayat downloads', bn: 'মদিনা মুসহাফের অফিসিয়াল সংস্করণ ও রেওয়ায়েত ডাউনলোড', zh: 'Official Madinah Mushaf editions & riwayat downloads', ja: 'Official Madinah Mushaf editions & riwayat downloads'},
    { name: 'Tamil Quran', url: 'https://tamilquran.org', emoji: '📗',
      en: 'Tamil, English & Arabic Quran translations', bn: 'তামিল, ইংরেজি ও আরবি কুরআন অনুবাদ', zh: 'Tamil, English & Arabic Quran translations', ja: 'Tamil, English & Arabic Quran translations'},
    { name: 'Quran.com App', url: 'https://quran.com/apps', emoji: '📱',
      en: 'Official free ad-free open-source Quran app', bn: 'অফিসিয়াল ফ্রি বিজ্ঞাপনহীন ওপেন-সোর্স কুরআন অ্যাপ', zh: 'Official free ad-free open-source Quran app', ja: 'Official free ad-free open-source Quran app'},
    { name: 'QuranO', url: 'https://qurano.com', emoji: '🌐',
      en: 'Word-by-word Quran & tafsir in 15 languages', bn: '১৫টি ভাষায় শব্দে-শব্দে কুরআন অনুবাদ ও তাফসির (তামিল, মালয়ালম, হিন্দি সহ)', zh: 'Word-by-word Quran & tafsir in 15 languages', ja: 'Word-by-word Quran & tafsir in 15 languages'},
    { name: 'Visual Quran', url: 'https://visualquran.info', emoji: '📊',
      en: 'Interactive Quran infographics, structure & statistics', bn: 'কুরআনের গঠন ও পরিসংখ্যানের ইন্টারেক্টিভ ইনফোগ্রাফিক', zh: 'Interactive Quran infographics, structure & statistics', ja: 'Interactive Quran infographics, structure & statistics'},
    { name: 'New Muslims eLearning', url: 'https://www.newmuslims.com', emoji: '🌱',
      en: 'Structured 10-level Islam course for reverts', bn: 'নওমুসলিমদের জন্য ধাপে ধাপে ইসলাম ও কুরআন শিক্ষা'},
    { name: 'New Muslim Academy', url: 'https://www.newmuslimacademy.org', emoji: '🤝',
      en: 'Free live Quran classes & mentorship for reverts', bn: 'নওমুসলিমদের জন্য বিনামূল্যে লাইভ কুরআন ক্লাস ও মেন্টরশিপ'},
    { name: 'Chinese Quran (Islamic Union HK)', url: 'https://www.islam.org.hk/cqse/cqse.asp', emoji: '🇨🇳',
      en: 'Chinese Quran translation by Islamic Union of Hong Kong', bn: 'চীনা ভাষায় কুরআন অনুবাদ (হংকং ইসলামিক ইউনিয়ন)'},
    { name: 'islam.de — Quran', url: 'https://islam.de/quran', emoji: '🇩🇪',
      en: "German Quran translation portal by Germany's Muslim council", bn: 'জার্মানির মুসলিম কাউন্সিলের জার্মান কুরআন অনুবাদ পোর্টাল' },
    { name: 'Quran Tab', url: 'https://chromewebstore.google.com/detail/quran-tab/afaihcdgkjebgabomemccdneglknjkdd', emoji: '🌐',
      en: 'New-tab verse with 40+ languages and reciters', bn: 'নতুন-ট্যাবে আয়াত, ৪০+ ভাষা ও কারী'},
    { name: 'Quran In New Tab', url: 'https://github.com/shahednasser/quran-extension', emoji: '🍃',
      en: 'Open-source new-tab Quran verses with nature images', bn: 'ওপেন-সোর্স নতুন-ট্যাব কুরআন আয়াত ও প্রকৃতির ছবি'},
  ] },
  { id: 'tafsir', emoji: '📚', titleKey: 'resources_cat_tafsir', items: [
    { name: 'AlTafsir.com', url: 'https://www.altafsir.com', emoji: '📚',
      en: "World's largest tafsir library — 110+ works, 18 languages", bn: 'বিশ্বের বৃহত্তম তাফসির গ্রন্থাগার — ১১০+ গ্রন্থ' },
    { name: 'Alim.org', url: 'https://www.alim.org', emoji: '📖',
      en: 'Translations, tafsir (Ibn Kathir, Maududi) & hadith', bn: 'অনুবাদ, তাফসির (ইবনে কাসির, মওদুদি) ও হাদিস', zh: 'Translations, tafsir (Ibn Kathir, Maududi) & hadith', ja: 'Translations, tafsir (Ibn Kathir, Maududi) & hadith'},
    { name: 'IslamAwakened', url: 'https://islamawakened.com', emoji: '🔤',
      en: 'Compare 70+ English translations verse by verse', bn: '৭০+ ইংরেজি অনুবাদ আয়াতভিত্তিক তুলনা'},
    { name: 'Quranx.com', url: 'https://quranx.com', emoji: '🔎',
      en: 'Search Quran, multiple tafsir & hadith together', bn: 'কুরআন, একাধিক তাফসির ও হাদিস একসাথে অনুসন্ধান', zh: 'Search Quran, multiple tafsir & hadith together', ja: 'Search Quran, multiple tafsir & hadith together'},
    { name: 'QuranEnc', url: 'https://quranenc.com/en/home', emoji: '🗂️',
      en: 'Encyclopedia of verified translations in 80+ languages', bn: '৮০+ ভাষায় যাচাইকৃত অনুবাদের বিশ্বকোষ', zh: 'Encyclopedia of verified translations in 80+ languages', ja: 'Encyclopedia of verified translations in 80+ languages'},
    { name: 'Parallel Quran', url: 'https://parallelquran.com', emoji: '📚',
      en: 'Five classical commentators shown side-by-side per verse', bn: 'পাঁচ শাস্ত্রীয় মুফাসসিরের তাফসির পাশাপাশি', zh: 'Five classical commentators shown side-by-side per verse', ja: 'Five classical commentators shown side-by-side per verse'},
    { name: 'QuranV', url: 'https://www.quranv.com', emoji: '🌐',
      en: 'Verse-by-verse translation comparison across many languages', bn: 'আয়াতভিত্তিক বহুভাষিক অনুবাদ তুলনা', zh: 'Verse-by-verse translation comparison across many languages', ja: 'Verse-by-verse translation comparison across many languages'},
    { name: 'English Quran', url: 'https://englishquran.com', emoji: '🔤',
      en: 'Compare English translations side-by-side with root dictionary', bn: 'ইংরেজি অনুবাদ পাশাপাশি তুলনা ও মূলশব্দ অভিধান'},
    { name: 'Yaqeen: Quran 30 for 30', url: 'https://yaqeeninstitute.org/series/quran-30-for-30', emoji: '🎬',
      en: 'Free thematic tafsir video series, juz by juz', bn: 'বিনামূল্যের বিষয়ভিত্তিক তাফসির ভিডিও সিরিজ'},
    { name: 'Tadabbur-e-Quran (Islahi)', url: 'https://amin-ahsan-islahi.org', emoji: '🧩',
      en: "Islahi's coherence-based (nazm) Quran tafsir in English", bn: 'ইসলাহীর নাযম-ভিত্তিক কুরআন তাফসির (ইংরেজি)' },
    { name: 'Tafhim al-Quran (Maududi)', url: 'https://tafheem.net', emoji: '📖',
      en: "Maududi's full English tafsir, free online", bn: 'মাওদূদীর তাফহীমুল কুরআন, সম্পূর্ণ ইংরেজি তাফসির' },
    { name: 'Tafsir Ibn Kathir', url: 'https://www.wordofallah.com/tafseer', emoji: '📕',
      en: 'Complete Tafsir Ibn Kathir in English online', bn: 'তাফসীর ইবনে কাসীর, সম্পূর্ণ ইংরেজি অনলাইনে', zh: 'Complete Tafsir Ibn Kathir in English online', ja: 'Complete Tafsir Ibn Kathir in English online'},
    { name: 'Maarif-ul-Quran (English)', url: 'https://www.australianislamiclibrary.org/maarif-ul-quran.html', emoji: '📗',
      en: "Mufti Shafi's 8-volume English tafsir, free", bn: 'মুফতি শফীর মাআরিফুল কুরআন, ইংরেজি ৮ খণ্ড ফ্রি' },
    { name: 'NAK Collection Tafsir', url: 'https://www.nakcollection.com/quran-tafsir.html', emoji: '🎙️',
      en: 'Free Nouman Ali Khan tafsir audio by surah', bn: 'নোমান আলী খানের ফ্রি তাফসির অডিও, সূরা অনুযায়ী'},
    { name: 'Tafsir.app', url: 'https://tafsir.app', emoji: '🔎',
      en: '60+ classical Arabic tafsirs with instant search', bn: '৬০+ ক্লাসিক্যাল আরবি তাফসির, তাৎক্ষণিক অনুসন্ধানসহ'},
    { name: 'Thafheem-ul-Quran (Malayalam)', url: 'https://thafheem.net', emoji: '📖',
      en: 'Malayalam Quran translation & tafsir', bn: 'মালয়ালম কুরআন অনুবাদ ও তাফসির', zh: 'Malayalam Quran translation & tafsir', ja: 'Malayalam Quran translation & tafsir'},
    { name: "Tafsir as-Sa'di (English, 10 vols)", url: 'https://archive.org/details/tafseer-as-sadi-by-shaykh-abdur-rahman-al-sadi-10-volume-set-english', emoji: '📘',
      en: "Full English Tafsir as-Sa'di, ten volumes", bn: 'সম্পূর্ণ ইংরেজি তাফসির আস-সাদি, দশ খণ্ড' },
    { name: 'Quran Malayalam', url: 'https://quranmalayalam.com/quran/', emoji: '📖',
      en: 'Malayalam Quran translation, Amani tafsir & audio', bn: 'মালয়ালম কুরআন অনুবাদ, আমানি তাফসির ও অডিও', zh: 'Malayalam Quran translation, Amani tafsir & audio', ja: 'Malayalam Quran translation, Amani tafsir & audio'},
    { name: 'Tamil Il Quran', url: 'https://www.tamililquran.com', emoji: '📗',
      en: 'Tamil Quran word-by-word, Ibn Kathir tafsir & audio', bn: 'তামিল কুরআন শব্দে-শব্দে, ইবনে কাসির তাফসির ও অডিও', zh: 'Tamil Quran word-by-word, Ibn Kathir tafsir & audio', ja: 'Tamil Quran word-by-word, Ibn Kathir tafsir & audio'},
    { name: 'Surah.my (Malay)', url: 'https://www.surah.my', emoji: '🇲🇾',
      en: 'Malay Quran translation reference (since 2007)', bn: 'মালয় ভাষায় কুরআন অনুবাদ', zh: 'Malay Quran translation reference (since 2007)', ja: 'Malay Quran translation reference (since 2007)'},
  ] },
  { id: 'audio', emoji: '🎧', titleKey: 'resources_cat_audio', items: [
    { name: 'EveryAyah', url: 'https://everyayah.com', emoji: '🎧',
      en: 'Ayah-by-ayah audio, many reciters, with timings', bn: 'আয়াতভিত্তিক অডিও, বহু কারি, টাইমিংসহ'},
    { name: 'QuranicAudio', url: 'https://quranicaudio.com', emoji: '🔊',
      en: 'High-quality recitation streaming & downloads, 80+ reciters', bn: 'উচ্চমানের তিলাওয়াত স্ট্রিমিং ও ডাউনলোড, ৮০+ কারি', zh: 'High-quality recitation streaming & downloads, 80+ reciters', ja: 'High-quality recitation streaming & downloads, 80+ reciters'},
    { name: 'MP3Quran', url: 'https://www.mp3quran.net/eng', emoji: '📻',
      en: 'Vast audio library, many reciters & narrations, radio', bn: 'বিশাল অডিও লাইব্রেরি, বহু কারি ও রেওয়ায়াত, রেডিও', zh: 'Vast audio library, many reciters & narrations, radio', ja: 'Vast audio library, many reciters & narrations, radio'},
    { name: 'Assabile', url: 'https://www.assabile.com', emoji: '🎙️',
      en: 'Free listen & download, 500+ reciters', bn: '৫০০+ কারির ফ্রি তিলাওয়াত শোনা ও ডাউনলোড', zh: 'Free listen & download, 500+ reciters', ja: 'Free listen & download, 500+ reciters'},
    { name: 'Tarteel AI', url: 'https://tarteel.ai', emoji: '🤖',
      en: 'AI memorization helper — detects recitation mistakes', bn: 'এআই হিফয সহায়ক — তিলাওয়াতের ভুল শনাক্ত করে', zh: 'AI memorization helper — detects recitation mistakes', ja: 'AI memorization helper — detects recitation mistakes'},
    { name: 'Quran Explorer', url: 'https://read.quranexplorer.com', emoji: '🎧',
      en: 'Read and listen with many reciters and tajweed colours', bn: 'বহু ক্বারি ও তাজবিদ রঙে পড়া-শোনা'},
    { name: 'Recite Quran', url: 'https://www.recitequran.com', emoji: '🔊',
      en: 'Word-by-word and tajweed recitation with translations', bn: 'শব্দে-শব্দে ও তাজবিদ তিলাওয়াত, অনুবাদসহ'},
    { name: 'House of Quran', url: 'https://www.houseofquran.com', emoji: '🕌',
      en: 'Word-by-word reciter and hifz tool with translation', bn: 'শব্দে-শব্দে ক্বারি ও হিফজ টুল, অনুবাদসহ'},
    { name: 'Quran Central', url: 'https://qurancentral.com', emoji: '🎧',
      en: '450+ reciters and lectures, free and ad-free', bn: '৪৫০+ ক্বারীর তিলাওয়াত ও লেকচার, বিজ্ঞাপনমুক্ত'},
    { name: 'IslamicFinder Quran', url: 'https://www.islamicfinder.org/quran/', emoji: '🔊',
      en: 'Quran audio & translation in 40+ languages', bn: '৪০+ ভাষায় কুরআন অডিও, অনুবাদ ও অনুসন্ধান', zh: 'Quran audio & translation in 40+ languages', ja: 'Quran audio & translation in 40+ languages'},
    { name: 'Quran Pro', url: 'https://islam.quanticapps.com/en/apps/quran-islamic-mobile-app/', emoji: '🎧',
      en: 'Free app: huge reciter library, offline, 30 languages', bn: 'ফ্রি অ্যাপ, বিশাল কারী সংগ্রহ, অফলাইন, ৩০ ভাষা', zh: 'Free app: huge reciter library, offline, 30 languages', ja: 'Free app: huge reciter library, offline, 30 languages'},
    { name: 'Muslim Central', url: 'https://muslimcentral.com', emoji: '🔊',
      en: "Huge free audio library of scholars' lectures", bn: 'স্কলারদের বক্তৃতার বিশাল বিনামূল্যে অডিও লাইব্রেরি' },
  ] },
  { id: 'arabic', emoji: '🔤', titleKey: 'resources_cat_arabic', items: [
    { name: 'Quranic Arabic Corpus', url: 'https://corpus.quran.com', emoji: '🔤',
      en: 'Word-by-word grammar, syntax & morphology treebank', bn: 'শব্দে-শব্দে ব্যাকরণ, বাক্যগঠন ও রূপতত্ত্ব', zh: 'Word-by-word grammar, syntax & morphology treebank', ja: 'Word-by-word grammar, syntax & morphology treebank'},
    { name: 'Arabic Almanac', url: 'https://ejtaal.net/aa', emoji: '📚',
      en: 'Root search across Lane, Hans Wehr & Hava dictionaries', bn: 'লেন, হ্যান্স ভেয়ার ও হাভা অভিধানে মূল-শব্দ খোঁজা', zh: 'Root search across Lane, Hans Wehr & Hava dictionaries', ja: 'Root search across Lane, Hans Wehr & Hava dictionaries'},
    { name: 'The Arabic Lexicon', url: 'https://arabiclexicon.hawramani.com', emoji: '🏛️',
      en: 'Searchable hyperdictionary of 47 classical works', bn: '৪৭টি ধ্রুপদী অভিধানের অনুসন্ধানযোগ্য সংগ্রহ', zh: 'Searchable hyperdictionary of 47 classical works', ja: 'Searchable hyperdictionary of 47 classical works'},
    { name: 'Madinah Arabic', url: 'https://www.madinaharabic.com', emoji: '🕌',
      en: 'Free 90+ lesson Arabic language & reading course', bn: 'বিনামূল্যে ৯০+ পাঠের আরবি ভাষা কোর্স', zh: 'Free 90+ lesson Arabic language & reading course', ja: 'Free 90+ lesson Arabic language & reading course'},
    { name: 'Bayyinah TV', url: 'https://explore.bayyinahtv.com/arabic', emoji: '📺',
      en: 'Structured Quranic Arabic course (Nahw, Sarf, Balagha)', bn: 'কাঠামোবদ্ধ কুরআনি আরবি কোর্স (নাহু, সরফ, বালাগাহ)', zh: 'Structured Quranic Arabic course (Nahw, Sarf, Balagha)', ja: 'Structured Quranic Arabic course (Nahw, Sarf, Balagha)'},
    { name: 'Al-Dirassa Tajweed', url: 'https://al-dirassa.com/en/tajweed-rules-online-for-free', emoji: '🎨',
      en: 'Free step-by-step tajweed rules lessons', bn: 'বিনামূল্যে ধাপে ধাপে তাজবীদ নিয়মের পাঠ', zh: 'Free step-by-step tajweed rules lessons', ja: 'Free step-by-step tajweed rules lessons'},
    { name: 'Learn Quran Roots', url: 'https://learnquranroots.com', emoji: '🌱',
      en: 'Learn Quranic root-word vocabulary with spaced repetition', bn: 'স্পেসড রিপিটিশনে কুরআনি মূলশব্দ শেখার টুল'},
    { name: 'QuranExcel', url: 'https://quranexcel.com', emoji: '📊',
      en: 'Word-for-word translation, morphology & data downloads', bn: 'শব্দে-শব্দে অনুবাদ, রূপতত্ত্ব ও ডেটা ডাউনলোড', zh: 'Word-for-word translation, morphology & data downloads', ja: 'Word-for-word translation, morphology & data downloads'},
    { name: 'Iqra: Quranic Words', url: 'https://apps.apple.com/us/app/iqra-quranic-words/id6760343334', emoji: '🗂️',
      en: '700+ frequent Quranic words via flashcards, free app', bn: '৭০০+ প্রচলিত কুরআনি শব্দ ফ্ল্যাশকার্ডে শেখা', zh: '700+ frequent Quranic words via flashcards, free app', ja: '700+ frequent Quranic words via flashcards, free app'},
    { name: 'TajweedMate', url: 'https://tajweedmate.com', emoji: '🎙️',
      en: 'Free AI app for tajweed and recitation practice', bn: 'এআই-ভিত্তিক তাজবিদ ও তিলাওয়াত অনুশীলন অ্যাপ'},
    { name: 'Bayyinah (Nouman Ali Khan) YouTube', url: 'https://www.youtube.com/@bayyinah', emoji: '▶️',
      en: "Nouman Ali Khan's free Quranic Arabic videos", bn: 'নোমান আলী খানের কুরআনি আরবি ইউটিউব' },
    { name: 'Uthmani Mushaf Calligraphy', url: 'https://freeislamiccalligraphy.com/the-uthmani-font-mushaf/', emoji: '✍️',
      en: 'Uthmani-script mushaf & Islamic calligraphy, free', bn: 'উসমানি লিপি মুসহাফ ও ক্যালিগ্রাফি', zh: 'Uthmani-script mushaf & Islamic calligraphy, free', ja: 'Uthmani-script mushaf & Islamic calligraphy, free'},
    { name: 'Calligraphy Qalam', url: 'https://calligraphyqalam.com', emoji: '✒️',
      en: 'Learn Arabic calligraphy styles, tools & process', bn: 'আরবি ক্যালিগ্রাফির শৈলী, সরঞ্জাম ও পদ্ধতি শিখুন', zh: 'Learn Arabic calligraphy styles, tools & process', ja: 'Learn Arabic calligraphy styles, tools & process'},
    { name: 'Khatarabic', url: 'https://khatarabic.com', emoji: '🖋️',
      en: 'Arabic calligraphy studio, tools & free courses', bn: 'আরবি ক্যালিগ্রাফি স্টুডিও, টুল ও ফ্রি কোর্স', zh: 'Arabic calligraphy studio, tools & free courses', ja: 'Arabic calligraphy studio, tools & free courses'},
    { name: 'Understand Al-Quran Academy', url: 'https://understandquran.com', emoji: '🎓',
      en: 'Free courses to understand 80% of Quran words', bn: '৮০% কুরআনি শব্দ বোঝার ফ্রি কোর্স ও ভিডিও', zh: 'Free courses to understand 80% of Quran words', ja: 'Free courses to understand 80% of Quran words'},
    { name: 'Quranic (getquranic)', url: 'https://www.getquranic.com', emoji: '🎮',
      en: 'Learn Quran words via stories, free-forever tier', bn: 'গল্পের মাধ্যমে কুরআনি শব্দ শেখা, ফ্রি টিয়ার', zh: 'Learn Quran words via stories, free-forever tier', ja: 'Learn Quran words via stories, free-forever tier'},
    { name: 'Quranle', url: 'https://www.quranle.com', emoji: '🟩',
      en: 'Wordle-style daily Quranic Arabic word game, free', bn: 'ওয়ার্ডল-স্টাইল কুরআনি আরবি শব্দ খেলা, ফ্রি', zh: 'Wordle-style daily Quranic Arabic word game, free', ja: 'Wordle-style daily Quranic Arabic word game, free'},
    { name: 'Quranic Grammar', url: 'https://www.quranic-grammar.com', emoji: '📝',
      en: 'Free Quranic Arabic grammar lessons, no signup', bn: 'বিনামূল্যে কুরআনি আরবি ব্যাকরণ পাঠ, সাইনআপ ছাড়াই', zh: 'Free Quranic Arabic grammar lessons, no signup', ja: 'Free Quranic Arabic grammar lessons, no signup'},
    { name: 'LinguaQuran', url: 'https://linguaquran.com', emoji: '🔤',
      en: 'Learn 500 frequent words covering 80% of Quran', bn: 'কুরআনের ৮০% জুড়ে থাকা ৫০০ শব্দ শিখুন', zh: 'Learn 500 frequent words covering 80% of Quran', ja: 'Learn 500 frequent words covering 80% of Quran'},
  ] },
  { id: 'tajweed', emoji: '🎨', titleKey: 'resources_cat_tajweed', items: [
    { name: 'Tilawa.ai', url: 'https://tilawa.ai/en/quran/', emoji: '🎨',
      en: 'Colour-coded tajweed Quran, word-by-word & audio', bn: 'রঙিন তাজভিদসহ অনলাইন কুরআন পাঠ', zh: 'Colour-coded tajweed Quran, word-by-word & audio', ja: 'Colour-coded tajweed Quran, word-by-word & audio'},
    { name: 'QuranMakkah Tajweed', url: 'https://quranmakkah.com/tajweed-quran', emoji: '🌈',
      en: 'Colour-coded tajweed reader with full rules guide', bn: 'রঙ-কোডেড তাজভিদ কুরআন ও নিয়মাবলী'},
    { name: 'Al-Dirassa Tajweed Course', url: 'https://al-dirassa.com/en/tajweed-rules-online-for-free', emoji: '🎓',
      en: 'Free step-by-step tajweed rules lessons', bn: 'বিনামূল্যে ধাপে ধাপে তাজবীদ নিয়মের পাঠ', zh: 'Free step-by-step tajweed rules lessons', ja: 'Free step-by-step tajweed rules lessons'},
  ] },
  { id: 'dua', emoji: '🤲', titleKey: 'resources_cat_dua', items: [
    { name: 'My Islam Duas', url: 'https://myislam.org/duas-and-dhikr/', emoji: '🤲',
      en: 'Duas from Quran & Sunnah with audio', bn: 'অডিওসহ কুরআন-সুন্নাহর দুআ সংকলন'},
    { name: 'Hisnul Muslim Online', url: 'https://ahadith.co.uk/fortressofthemuslim.php', emoji: '🛡️',
      en: 'Fortress of the Muslim duas, Arabic with references', bn: 'হিসনুল মুসলিম দুআ অনলাইনে, রেফারেন্সসহ'},
    { name: 'Hisnul Muslim (Falah)', url: 'https://falah.io/en/hisnul-muslim/', emoji: '🤲',
      en: 'Fortress of the Muslim duas with audio, ad-free', bn: 'হিসনুল মুসলিমের দোয়া অডিওসহ, বিজ্ঞাপনমুক্ত'},
    { name: 'Azkar.me', url: 'https://azkar.me/en', emoji: '📿',
      en: 'Adhkar tool with counter from Hisnul Muslim', bn: 'হিসনুল মুসলিম থেকে আযকার টুল ও কাউন্টার'},
    { name: 'Life with Allah — Dhikr & Dua', url: 'https://lifewithallah.com/dhikr-dua/', emoji: '🤲',
      en: 'Morning, evening adhkar and daily duas', bn: 'সকাল-সন্ধ্যার আযকার ও দৈনিক দোয়া'},
    { name: 'Tasbih.org', url: 'https://www.tasbih.org', emoji: '🔢',
      en: 'Free online tasbih dhikr tally counter', bn: 'ফ্রি অনলাইন তাসবিহ যিকির গণনা যন্ত্র', zh: 'Free online tasbih dhikr tally counter', ja: 'Free online tasbih dhikr tally counter'},
  ] },
  { id: 'seerah', emoji: '🌙', titleKey: 'resources_cat_seerah', items: [
    { name: 'The Seerah App', url: 'https://www.seerahapp.com', emoji: '🌙',
      en: "Learn the Prophet's life in bite-sized chapters", bn: 'নবীজির জীবনী সহজ অধ্যায়ে শেখা' },
    { name: 'Yaqeen: Life of the Prophet', url: 'https://yaqeeninstitute.org/topic/life-of-the-prophet-seerah', emoji: '📖',
      en: 'Seerah videos, papers and resources, free', bn: 'নবীজির জীবনী নিয়ে ভিডিও ও প্রবন্ধ'},
    { name: 'Seerah Atlas', url: 'https://seerahatlas.com/en', emoji: '🗺️',
      en: 'Interactive seerah atlas: maps and timeline', bn: 'ইন্টারেক্টিভ সিরাত অ্যাটলাস: মানচিত্র ও সময়রেখা'},
    { name: 'SirahMaps', url: 'https://sirahmaps.com', emoji: '📍',
      en: "Interactive maps of the Prophet's life", bn: 'নবীজির জীবনের ইন্টারেক্টিভ মানচিত্র' },
    { name: 'LearnSeerah', url: 'https://learnseerah.com/en/maps/interactive', emoji: '🕰️',
      en: 'Seerah content, interactive maps and timelines', bn: 'সিরাত, ইন্টারেক্টিভ মানচিত্র ও সময়রেখা'},
    { name: 'Stories of the Prophets (Ibn Kathir)', url: 'https://archive.org/details/stories-of-the-prophets-by-ibn-kathir-english-pdf', emoji: '📖',
      en: "Ibn Kathir's stories of the prophets, free", bn: 'ইবনে কাসিরের নবীদের কাহিনি, বিনামূল্যে' },
    { name: 'Madain Project', url: 'https://madainproject.com', emoji: '🏛️',
      en: 'Abrahamic history & archaeology of seerah sites', bn: 'সীরাহর স্থানসমূহের ইতিহাস ও প্রত্নতত্ত্ব বিশ্বকোষ', zh: 'Abrahamic history & archaeology of seerah sites', ja: 'Abrahamic history & archaeology of seerah sites'},
  ] },
  { id: 'memorization', emoji: '🧠', titleKey: 'resources_cat_memorization', items: [
    { name: 'Hafiz Quran', url: 'https://hafiz-quran.com', emoji: '🧠',
      en: 'Free ad-free hifz tool using FSRS spaced repetition', bn: 'FSRS স্পেসড রিপিটিশনে বিনামূল্যের হিফজ টুল', zh: 'Free ad-free hifz tool using FSRS spaced repetition', ja: 'Free ad-free hifz tool using FSRS spaced repetition'},
    { name: 'Retain Quran', url: 'https://retainquranapp.com', emoji: '🔁',
      en: 'Free spaced-repetition flashcard app for memorization', bn: 'স্পেসড রিপিটিশন ফ্ল্যাশকার্ডে কুরআন মুখস্থ অ্যাপ'},
    { name: 'Ayah: Quran App', url: 'https://ayahapp.com', emoji: '📱',
      en: 'Beautiful, ad-free free Quran reading app', bn: 'সুন্দর, বিজ্ঞাপনহীন বিনামূল্যের কুরআন অ্যাপ', zh: 'Beautiful, ad-free free Quran reading app', ja: 'Beautiful, ad-free free Quran reading app'},
    { name: 'The Hifz Project', url: 'https://thehifzproject.com', emoji: '🧠',
      en: 'Free spaced-repetition memorization, all 114 surahs', bn: 'স্পেসড-রিপিটিশনে ফ্রি কুরআন হিফজ, সব ১১৪ সূরা', zh: 'Free spaced-repetition memorization, all 114 surahs', ja: 'Free spaced-repetition memorization, all 114 surahs'},
    { name: 'Quran Companion Tools', url: 'https://qurantools.io/?lang=en', emoji: '🧰',
      en: 'Free hifz tracker, mushaf reader & recitation grading', bn: 'বিনামূল্যের হিফজ ট্র্যাকার, মুসহাফ রিডার ও গ্রেডিং', zh: 'Free hifz tracker, mushaf reader & recitation grading', ja: 'Free hifz tracker, mushaf reader & recitation grading'},
  ] },
  { id: 'hadith', emoji: '📜', titleKey: 'resources_cat_hadith', items: [
    { name: 'Sunnah.com', url: 'https://sunnah.com', emoji: '📜',
      en: 'Authentic hadith collections, searchable, many languages', bn: 'সহীহ হাদিস সংকলন, খোঁজযোগ্য, একাধিক ভাষায় ফ্রি', zh: 'Authentic hadith collections, searchable, many languages', ja: 'Authentic hadith collections, searchable, many languages'},
    { name: 'HadeethEnc', url: 'https://hadeethenc.com/en/home', emoji: '📚',
      en: 'Explained hadith encyclopedia in 70 languages', bn: '৭০ ভাষায় ব্যাখ্যাসহ অনূদিত হাদিস বিশ্বকোষ', zh: 'Explained hadith encyclopedia in 70 languages', ja: 'Explained hadith encyclopedia in 70 languages'},
    { name: 'Dorar Encyclopedias', url: 'https://dorar.net/en', emoji: '📜',
      en: 'Hadith grading & scholarly Islamic encyclopedias', bn: 'হাদিসের বিশুদ্ধতা যাচাই ও ইসলামি জ্ঞানকোষ', zh: 'Hadith grading & scholarly Islamic encyclopedias', ja: 'Hadith grading & scholarly Islamic encyclopedias'},
    { name: 'SunnahOnline (Hadith Sciences)', url: 'https://sunnahonline.com/library/fiqh-and-sunnah/277-introduction-to-the-sciences-of-hadith', emoji: '📜',
      en: 'Hadith sciences (mustalah) & Islamic library', bn: 'হাদিস শাস্ত্র (মুস্তালাহ) ও ইসলামিক লাইব্রেরি', zh: 'Hadith sciences (mustalah) & Islamic library', ja: 'Hadith sciences (mustalah) & Islamic library'},
  ] },
  { id: 'kids', emoji: '🧒', titleKey: 'resources_cat_kids', items: [
    { name: 'Kids Land (Farhat Hashmi)', url: 'https://kids.farhathashmi.com', emoji: '🧒',
      en: 'Free Quran stories, games and duas for children', bn: 'শিশুদের জন্য বিনামূল্যের কুরআন গল্প, খেলা ও দুআ'},
    { name: 'Quran Stories 4 Kids', url: 'https://apps.apple.com/us/app/quran-stories-4-kids-prophets/id1578082367', emoji: '🎨',
      en: 'Animated narrated prophet stories app in 16 languages', bn: 'নবীদের অ্যানিমেটেড বর্ণিত গল্পের অ্যাপ', zh: 'Animated narrated prophet stories app in 16 languages', ja: 'Animated narrated prophet stories app in 16 languages'},
    { name: 'Islam 4 Kids', url: 'https://www.islam4kids.org', emoji: '🧒',
      en: 'Free Islamic games, stories & printable worksheets', bn: 'শিশুদের জন্য ফ্রি ইসলামিক গেম, গল্প ও ওয়ার্কশিট', zh: 'Free Islamic games, stories & printable worksheets', ja: 'Free Islamic games, stories & printable worksheets'},
    { name: 'IQRA Cartoon', url: 'https://iqracartoon.com', emoji: '🎬',
      en: 'Free nonprofit animated Quran and prophet stories', bn: 'ফ্রি অলাভজনক অ্যানিমেটেড কুরআন ও নবীদের গল্প'},
    { name: 'ILMA Education (Printables)', url: 'https://www.ilmaeducation.com/p/free-downloads.html', emoji: '🖍️',
      en: 'Free printable Islamic worksheets & flashcards for kids', bn: 'শিশুদের জন্য ফ্রি ইসলামিক ওয়ার্কশিট ও ফ্ল্যাশকার্ড'},
    { name: 'Adab Adventures', url: 'https://www.adabadventures.com', emoji: '🧒',
      en: 'Free ad-free Islamic audio stories for kids', bn: 'বাচ্চাদের জন্য বিনামূল্যে বিজ্ঞাপনহীন ইসলামি অডিও গল্প'},
    { name: 'Noor Kids Printables', url: 'https://noorkids.com/pages/printables', emoji: '🎨',
      en: 'Free printable Islamic activities for children', bn: 'শিশুদের জন্য বিনামূল্যে প্রিন্টেবল ইসলামিক অ্যাক্টিভিটি'},
    { name: 'The Family & Youth Institute', url: 'https://thefyi.org', emoji: '👪',
      en: 'Research-backed Muslim family & parenting resources', bn: 'গবেষণাভিত্তিক মুসলিম পরিবার ও প্যারেন্টিং রিসোর্স', zh: 'Research-backed Muslim family & parenting resources', ja: 'Research-backed Muslim family & parenting resources'},
  ] },
  { id: 'courses', emoji: '🎓', titleKey: 'resources_cat_courses', items: [
    { name: 'SeekersGuidance Quran Tafsir', url: 'https://academy.seekersguidance.org/enrol/index.php?id=552', emoji: '📖',
      en: 'Free complete Quran tafsir in short scholar-led lessons', bn: 'স্কলারদের সংক্ষিপ্ত পাঠে বিনামূল্যে সম্পূর্ণ কুরআন তাফসির', zh: 'Free complete Quran tafsir in short scholar-led lessons', ja: 'Free complete Quran tafsir in short scholar-led lessons'},
    { name: 'Arabic101', url: 'https://arabic101.org', emoji: '🔤',
      en: 'Free Quranic Arabic video courses and ebooks', bn: 'বিনামূল্যে কুরআনি আরবি ভিডিও কোর্স ও ইবুক'},
    { name: 'Quran Revolution (AlMaghrib)', url: 'https://www.youtube.com/c/QuranRevolution', emoji: '🎵',
      en: "AlMaghrib's free tajweed & recitation coaching channel", bn: 'আলমাগরিবের বিনামূল্যে তাজবিদ ও তিলাওয়াত প্রশিক্ষণ চ্যানেল' },
    { name: 'Bayyinah Podcast (Nouman Ali Khan)', url: 'https://podcasts.apple.com/us/podcast/nouman-ali-khan-bayyinah-podcast/id1773328879', emoji: '🎙️',
      en: "Nouman Ali Khan's free deep-dive Quran podcast", bn: 'নোমান আলী খানের বিনামূল্যে গভীর কুরআন পডকাস্ট' },
    { name: 'Qalam Tafsir Podcast', url: 'https://www.qalaminstitute.org/category/podcast/tafsir-tuesdays-app/', emoji: '🎧',
      en: "Abdul Nasir Jangda's free verse-by-verse tafsir podcast", bn: 'আব্দুল নাসির জাংদার বিনামূল্যে আয়াতভিত্তিক তাফসির পডকাস্ট' },
    { name: 'Yasir Qadhi Quran Tafsir Series', url: 'https://www.youtube.com/playlist?list=PLYO6Oz7uwCSiIvS8fBim58larO1tRs9uI', emoji: '📺',
      en: "Yasir Qadhi's free Quran tafsir video series", bn: 'ইয়াসির কাধির বিনামূল্যে কুরআন তাফসির ভিডিও সিরিজ' },
    { name: 'Yasir Qadhi Seerah Series', url: 'https://www.youtube.com/playlist?list=PLAEA99D24CA2F9A8F', emoji: '🕌',
      en: "Yasir Qadhi's free 100-episode Seerah lecture series", bn: 'ইয়াসির কাধির বিনামূল্যে ১০০ পর্বের সিরাহ বক্তৃতা সিরিজ' },
    { name: 'Introduction to the Quran (Notre Dame, edX)', url: 'https://www.edx.org/learn/islam/university-of-notre-dame-introduction-to-the-quran-the-scripture-of-islam', emoji: '🎓',
      en: 'Notre Dame university Quran course, free to audit', bn: 'নটর ডেম বিশ্ববিদ্যালয়ের কুরআন কোর্স, বিনামূল্যে অডিট', zh: 'Notre Dame university Quran course, free to audit', ja: 'Notre Dame university Quran course, free to audit'},
    { name: 'Islam Through Its Scriptures (Harvard)', url: 'https://pll.harvard.edu/course/islam-through-its-scriptures', emoji: '🏛️',
      en: 'Harvard course on the Quran, free audit', bn: 'কুরআন নিয়ে হার্ভার্ড কোর্স, বিনামূল্যে অডিট'},
    { name: "The Birmingham Qur'an (FutureLearn)", url: 'https://www.futurelearn.com/courses/birmingham-quran', emoji: '📜',
      en: 'Birmingham University course on ancient Quran manuscript', bn: 'প্রাচীন কুরআন পাণ্ডুলিপি নিয়ে বার্মিংহাম বিশ্ববিদ্যালয়ের কোর্স', zh: 'Birmingham University course on ancient Quran manuscript', ja: 'Birmingham University course on ancient Quran manuscript'},
    { name: 'New Muslim Guide', url: 'https://www.newmuslimguide.com/en', emoji: '🧭',
      en: 'Illustrated worship basics guide in 26 languages', bn: '২৬ ভাষায় সচিত্র ইবাদতের মৌলিক গাইড', zh: 'Illustrated worship basics guide in 26 languages', ja: 'Illustrated worship basics guide in 26 languages'},
    { name: 'Rabata', url: 'https://www.rabata.org', emoji: '🌸',
      en: 'Women-led Islamic scholarship & free resources', bn: 'নারী-নেতৃত্বাধীন ইসলামিক শিক্ষা ও ফ্রি রিসোর্স', zh: 'Women-led Islamic scholarship & free resources', ja: 'Women-led Islamic scholarship & free resources'},
    { name: 'International Open University', url: 'https://iou.edu.gm', emoji: '🎓',
      en: 'Free Islamic studies diploma & certificate courses', bn: 'ফ্রি ইসলামিক স্টাডিজ ডিপ্লোমা ও সার্টিফিকেট কোর্স', zh: 'Free Islamic studies diploma & certificate courses', ja: 'Free Islamic studies diploma & certificate courses'},
  ] },
  { id: 'academic', emoji: '📜', titleKey: 'resources_cat_academic', items: [
    { name: 'Encyclopedia of Variant Readings (EvQ)', url: 'https://digitalhumanities.fas.harvard.edu/projects/evq/', emoji: '📖',
      en: 'Harvard open encyclopedia of Quranic variant readings', bn: 'কুরআনের কিরাআত পাঠের হার্ভার্ড ওপেন এনসাইক্লোপিডিয়া', zh: 'Harvard open encyclopedia of Quranic variant readings', ja: 'Harvard open encyclopedia of Quranic variant readings'},
    { name: 'Noon (nQuran)', url: 'https://nquran.com', emoji: '🎨',
      en: "Ten qira'at readings shown in coloured Arabic", bn: 'রঙিন আরবিতে দশ কিরাআত পাঠ প্রদর্শন' },
    { name: 'Cambridge Digital Library (Islamic)', url: 'https://cudl.lib.cam.ac.uk/collections/islamic', emoji: '📜',
      en: 'Cambridge digitized Islamic and Quran manuscripts', bn: 'কেমব্রিজের ডিজিটাল ইসলামিক ও কুরআন পাণ্ডুলিপি'},
    { name: 'Digital Mushaf Project (Bodleian)', url: 'https://digitalmushaf.bodleian.ox.ac.uk', emoji: '🧩',
      en: 'Oxford reconstructs dispersed early Quran manuscript folios', bn: 'অক্সফোর্ডের বিক্ষিপ্ত প্রাচীন কুরআন পাণ্ডুলিপি পুনর্গঠন', zh: 'Oxford reconstructs dispersed early Quran manuscript folios', ja: 'Oxford reconstructs dispersed early Quran manuscript folios'},
    { name: 'Harvard Islamic Heritage Project', url: 'https://curiosity.lib.harvard.edu/islamic-heritage-project', emoji: '🏛️',
      en: "Harvard's digitized Islamic manuscripts and Qurans", bn: 'হার্ভার্ডের ডিজিটাল ইসলামিক পাণ্ডুলিপি ও কুরআন' },
    { name: "GloQur — The Global Qur'an", url: 'https://gloqur.de', emoji: '🌍',
      en: 'Scholarly research on worldwide Quran translations', bn: 'বিশ্বব্যাপী কুরআন অনুবাদ নিয়ে গবেষণা প্রকল্প', zh: 'Scholarly research on worldwide Quran translations', ja: 'Scholarly research on worldwide Quran translations'},
    { name: 'IQSA', url: 'https://iqsaweb.org', emoji: '🎓',
      en: 'Academic society and open Quranic studies journals', bn: 'কুরআন গবেষণার একাডেমিক সংগঠন ও জার্নাল'},
    { name: 'KITAB / OpenITI', url: 'https://kitab-project.org', emoji: '🗄️',
      en: 'Open Arabic text corpus with reuse analysis', bn: 'উন্মুক্ত আরবি টেক্সট কর্পাস ও পুনঃব্যবহার বিশ্লেষণ'},
    { name: 'al-Maktaba al-Shamela', url: 'https://shamela.ws', emoji: '📚',
      en: 'Vast free library of classical Arabic Islamic texts', bn: 'শাস্ত্রীয় আরবি তাফসির ও ইসলামি গ্রন্থাগার', zh: 'Vast free library of classical Arabic Islamic texts', ja: 'Vast free library of classical Arabic Islamic texts'},
    { name: 'Qatar Digital Library', url: 'https://www.qdl.qa/en', emoji: '📜',
      en: 'Free archive of Arabic scientific manuscripts', bn: 'আরবি বৈজ্ঞানিক পাণ্ডুলিপির বিনামূল্যের সংরক্ষণাগার', zh: 'Free archive of Arabic scientific manuscripts', ja: 'Free archive of Arabic scientific manuscripts'},
    { name: 'Arabic Collections Online', url: 'https://aco.dlib.nyu.edu', emoji: '📚',
      en: "NYU's free open library of public-domain Arabic books", bn: 'এনওয়াইইউ-এর পাবলিক-ডোমেইন আরবি বই লাইব্রেরি' },
    { name: 'Ghazali.org', url: 'https://www.ghazali.org', emoji: '🕯️',
      en: 'Complete al-Ghazali digital library & translations', bn: 'ইমাম গাযালির পূর্ণাঙ্গ ডিজিটাল লাইব্রেরি ও অনুবাদ', zh: 'Complete al-Ghazali digital library & translations', ja: 'Complete al-Ghazali digital library & translations'},
    { name: 'Renovatio (Zaytuna)', url: 'https://renovatio.zaytuna.edu', emoji: '🖋️',
      en: 'Zaytuna College free journal of Islamic thought', bn: 'ইসলামি চিন্তাধারায় যায়তুনা কলেজের ফ্রি জার্নাল', zh: 'Zaytuna College free journal of Islamic thought', ja: 'Zaytuna College free journal of Islamic thought'},
    { name: 'Maqasid Institute', url: 'https://maqasid.org/education/', emoji: '🎓',
      en: 'Maqasid studies, free e-library & journal', bn: 'মাকাসিদ অধ্যয়ন, ফ্রি ই-লাইব্রেরি ও জার্নাল', zh: 'Maqasid studies, free e-library & journal', ja: 'Maqasid studies, free e-library & journal'},
    { name: 'AAOIFI', url: 'https://aaoifi.com/?lang=en', emoji: '💰',
      en: 'Islamic finance ethics & Shariah standards', bn: 'ইসলামিক ফাইন্যান্স নৈতিকতা ও শরিয়াহ মান', zh: 'Islamic finance ethics & Shariah standards', ja: 'Islamic finance ethics & Shariah standards'},
    { name: 'Hijri Timeline', url: 'https://www.hijritimeline.com', emoji: '📅',
      en: 'Interactive Islamic history events timeline', bn: 'ইসলামি ইতিহাসের ইন্টারেক্টিভ সময়রেখা', zh: 'Interactive Islamic history events timeline', ja: 'Interactive Islamic history events timeline'},
    { name: 'OER Project: The Islamic World', url: 'https://www.oerproject.com/topics/the-islamic-world', emoji: '🌍',
      en: 'Free Islamic world history maps and lessons', bn: 'ইসলামি বিশ্ব ইতিহাসের বিনামূল্যের মানচিত্র ও পাঠ'},
    { name: 'Sapience Institute', url: 'https://www.sapienceinstitute.org/read/', emoji: '💡',
      en: 'Intellectual answers to doubts about Islam', bn: 'ইসলাম নিয়ে সংশয়ের বুদ্ধিবৃত্তিক উত্তর', zh: 'Intellectual answers to doubts about Islam', ja: 'Intellectual answers to doubts about Islam'},
    { name: 'Dawah Institute', url: 'https://dawah.ac', emoji: '🤝',
      en: 'Support and resources for new Muslims', bn: 'নতুন মুসলিমদের জন্য সহায়তা ও রিসোর্স'},
  ] },
  { id: 'dev', emoji: '🛠️', titleKey: 'resources_cat_dev', items: [
    { name: 'Quran Foundation API', url: 'https://api-docs.quran.foundation', emoji: '⚙️',
      en: 'Official Quran.com API: verses, translations, tafsir, audio', bn: 'কুরআন.com এর অফিসিয়াল API: আয়াত, অনুবাদ, তাফসির', zh: 'Official Quran.com API: verses, translations, tafsir, audio', ja: 'Official Quran.com API: verses, translations, tafsir, audio'},
    { name: 'Al Quran Cloud API', url: 'https://alquran.cloud/api', emoji: '☁️',
      en: 'Free REST API: text, audio, translations, mushaf', bn: 'ফ্রি REST API: টেক্সট, অডিও, অনুবাদ, মুসহাফ', zh: 'Free REST API: text, audio, translations, mushaf', ja: 'Free REST API: text, audio, translations, mushaf'},
    { name: 'Tanzil', url: 'https://tanzil.net', emoji: '✅',
      en: 'Verified Uthmani Quran text & translations for download', bn: 'যাচাইকৃত উসমানি কুরআন টেক্সট ও অনুবাদ ডাউনলোড'},
    { name: 'Quranic Universal Library', url: 'https://qul.tarteel.ai', emoji: '🧰',
      en: 'Open data hub: translations, tafsir, audio, fonts, layouts', bn: 'উন্মুক্ত ডেটা হাব: অনুবাদ, তাফসির, অডিও, ফন্ট', zh: 'Open data hub: translations, tafsir, audio, fonts, layouts', ja: 'Open data hub: translations, tafsir, audio, fonts, layouts'},
    { name: 'KFGQPC Fonts', url: 'https://fonts.qurancomplex.gov.sa/en/', emoji: '🅰️',
      en: 'Official King Fahd Complex Uthmanic Quran fonts', bn: 'কিং ফাহাদ কমপ্লেক্সের অফিসিয়াল উসমানি কুরআন ফন্ট', zh: 'Official King Fahd Complex Uthmanic Quran fonts', ja: 'Official King Fahd Complex Uthmanic Quran fonts'},
    { name: 'Corpus Coranicum', url: 'https://corpuscoranicum.org/en', emoji: '📜',
      en: 'Academic database of early manuscripts & variant readings', bn: 'প্রাচীন পাণ্ডুলিপি ও পাঠভেদের একাডেমিক ডেটাবেস', zh: 'Academic database of early manuscripts & variant readings', ja: 'Academic database of early manuscripts & variant readings'},
    { name: 'fawazahmed0 Quran API', url: 'https://github.com/fawazahmed0/quran-api', emoji: '🔌',
      en: 'Free CDN Quran API: 90+ languages, 440+ translations', bn: 'ফ্রি সিডিএন কুরআন API: ৯০+ ভাষা, ৪৪০+ অনুবাদ', zh: 'Free CDN Quran API: 90+ languages, 440+ translations', ja: 'Free CDN Quran API: 90+ languages, 440+ translations'},
    { name: 'quran-json (risan)', url: 'https://github.com/risan/quran-json', emoji: '📦',
      en: 'Quran text, transliteration and translations in JSON', bn: 'JSON ফরম্যাটে কুরআন টেক্সট, লিপ্যন্তর ও অনুবাদ'},
    { name: 'quran-align', url: 'https://github.com/cpfair/quran-align', emoji: '⏱️',
      en: 'Word-accurate audio timestamps for many reciters', bn: 'বহু কারীর জন্য শব্দভিত্তিক অডিও টাইমস্ট্যাম্প'},
    { name: 'Quranic Treebank (NoorBayan)', url: 'https://github.com/NoorBayan/Quranic', emoji: '🌳',
      en: 'Open Quran morphology and syntax treebank dataset', bn: 'উন্মুক্ত কুরআন রূপতত্ত্ব ও বাক্যতত্ত্ব ট্রিব্যাংক ডেটাসেট'},
    { name: 'DigitalKhatt', url: 'https://github.com/DigitalKhatt', emoji: '🖋️',
      en: 'Open-source Quran typesetting with dynamic Arabic fonts', bn: 'গতিশীল আরবি ফন্টসহ ওপেন-সোর্স কুরআন টাইপসেটিং'},
    { name: 'Amiri Font', url: 'https://aliftype.com/amiri/', emoji: '🔤',
      en: 'Classical Naskh Arabic font, free SIL license', bn: 'ধ্রুপদী নাসখ আরবি ফন্ট, ফ্রি SIL লাইসেন্স', zh: 'Classical Naskh Arabic font, free SIL license', ja: 'Classical Naskh Arabic font, free SIL license'},
    { name: 'Scheherazade New', url: 'https://software.sil.org/scheherazade/', emoji: '✒️',
      en: 'SIL Naskh Arabic font supporting Quranic text', bn: 'কুরআনি টেক্সট সমর্থনকারী SIL নাসখ আরবি ফন্ট', zh: 'SIL Naskh Arabic font supporting Quranic text', ja: 'SIL Naskh Arabic font supporting Quranic text'},
    { name: 'UmmahAPI', url: 'https://ummahapi.com', emoji: '🔗',
      en: 'Free keyless Quran API: random verse and translations', bn: 'ফ্রি কী-বিহীন কুরআন API: এলোমেলো আয়াত ও অনুবাদ'},
    { name: 'Tafsir API (spa5k)', url: 'https://github.com/spa5k/tafsir_api', emoji: '📚',
      en: 'Free tafsir API, 120+ commentaries, no limits', bn: 'বিনামূল্যে তাফসির API, ১২০+ তাফসির, সীমাহীন', zh: 'Free tafsir API, 120+ commentaries, no limits', ja: 'Free tafsir API, 120+ commentaries, no limits'},
  ] },
  { id: 'bangla', emoji: '🇧🇩', titleKey: 'resources_cat_bangla', items: [
    { name: 'Al Quran Digital — Islamic Foundation', url: 'https://www.quran.gov.bd', emoji: '🇧🇩',
      en: 'Official Bangladesh govt Quran: Arabic, Bangla, English, audio', bn: 'সরকারি ডিজিটাল কুরআন: আরবি, বাংলা, ইংরেজি ও অডিও', zh: 'Official Bangladesh govt Quran: Arabic, Bangla, English, audio', ja: 'Official Bangladesh govt Quran: Arabic, Bangla, English, audio'},
    { name: 'Hadithbd', url: 'https://www.hadithbd.com', emoji: '📚',
      en: 'Bangla Quran, tafsir & 90,000+ hadith & Islamic books', bn: 'বাংলা কুরআন, তাফসির ও ৯০,০০০+ হাদিস ও ইসলামিক বই', zh: 'Bangla Quran, tafsir & 90,000+ hadith & Islamic books', ja: 'Bangla Quran, tafsir & 90,000+ hadith & Islamic books'},
    { name: 'iHadis', url: 'https://ihadis.com', emoji: '🕌',
      en: '49,000+ authentic hadith in Bangla (IRD Foundation)', bn: 'আইআরডি ফাউন্ডেশনের ৪৯,০০০+ সহিহ হাদিস বাংলায়', zh: '49,000+ authentic hadith in Bangla (IRD Foundation)', ja: '49,000+ authentic hadith in Bangla (IRD Foundation)'},
    { name: 'Quraner Alo', url: 'https://quraneralo.com', emoji: '💡',
      en: 'Authentic Bangla Islamic articles, books & lectures', bn: 'নির্ভরযোগ্য বাংলা ইসলামিক প্রবন্ধ, বই ও লেকচার', zh: 'Authentic Bangla Islamic articles, books & lectures', ja: 'Authentic Bangla Islamic articles, books & lectures'},
    { name: 'Quran Hadith BD', url: 'https://www.quranhadithbd.com', emoji: '📙',
      en: 'Bengali Quran, tafsir & hadith', bn: 'বাংলা কুরআন, তাফসির ও হাদিস', zh: 'Bengali Quran, tafsir & hadith', ja: 'Bengali Quran, tafsir & hadith'},
    { name: 'Quran.com (Bengali)', url: 'https://quran.com/bn', emoji: '🌐',
      en: 'Global Quran platform with a Bengali interface', bn: 'বাংলা ইন্টারফেসসহ বিশ্বমানের কুরআন প্ল্যাটফর্ম'},
  ] },
];

class ResourcesView {
  constructor() {
    this.container = document.getElementById('resources-container');
    if (!this.container) return;
    this.language = (typeof appSettings !== 'undefined' && appSettings) ? appSettings.get('language') : 'en';
    this.rendered = false;

    window.addEventListener('tabChanged', (e) => { if (e.detail.tabId === 'resources') this.render(); });
    window.addEventListener('settingChanged', (e) => {
      if (e.detail.key === 'language') { this.language = e.detail.value; if (this.rendered) this.render(); }
    });
  }

  tt(key) { return t(key, this.language); }
  esc(s) { return String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])); }
  desc(item) { return item[this.language] || item.en; }

  render() {
    this.rendered = true;
    const lang = this.language;
    this.container.innerHTML = `
      <div class="w-full max-w-5xl mx-auto">
        <div class="text-center mb-2">
          <p class="text-gray-500 dark:text-gray-400 text-sm">${this.tt('resources_subtitle')}</p>
        </div>
        <p class="text-xs text-gray-400 dark:text-gray-500 text-center mb-6">🔗 ${this.tt('resources_note')}</p>
        ${RESOURCES_DATA.map(cat => `
          <section class="mb-8">
            <h3 class="flex items-center gap-2 text-lg font-bold mb-3">
              <span aria-hidden="true">${cat.emoji}</span><span>${this.tt(cat.titleKey)}</span>
            </h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              ${cat.items.map(it => `
                <a href="${this.esc(it.url)}" target="_blank" rel="noopener noreferrer"
                   class="group flex flex-col gap-1 p-4 rounded-xl bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700
                          hover:border-primary hover:shadow-md transition-all">
                  <span class="flex items-center gap-2 font-semibold text-gray-800 dark:text-gray-100">
                    <span class="text-lg" aria-hidden="true">${it.emoji}</span>
                    <span class="flex-1 min-w-0 truncate">${this.esc(it.name)}</span>
                    <span class="text-gray-300 dark:text-gray-600 group-hover:text-primary dark:group-hover:text-blue-400 transition-colors" aria-hidden="true">↗</span>
                  </span>
                  <span class="text-xs text-gray-500 dark:text-gray-400 leading-relaxed" dir="auto">${this.esc(this.desc(it))}</span>
                  <span class="text-[0.65rem] text-gray-400 dark:text-gray-500 truncate" dir="ltr">${this.esc(it.url.replace(/^https?:\/\//, ''))}</span>
                </a>`).join('')}
            </div>
          </section>`).join('')}
        <p class="text-xs text-gray-400 dark:text-gray-500 text-center mt-2 mb-8">${this.tt('resources_disclaimer')}</p>
      </div>`;
  }
}

let resourcesView;
document.addEventListener('DOMContentLoaded', () => { resourcesView = new ResourcesView(); });
